export const seedDB = [
  {
    name: 'America Chavez (Young Avengers)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1608151370/mpq/america4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'yellow',
    power_three_color: 'green',
    feedees: 'Jessica Jones (Alias Investigations)',
    feeders: 'none',
    char_level: 70,
  },
  {
    name: 'Angel (All New X-Men)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1608151683/mpq/angel3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'black',
    power_three_color: 'green',
    feedees: 'Nightcrawler (Classic), Jean Grey (All New X-Men)',
    feeders: 'none',
    char_level: 40,
  },
  {
    name: 'Ant-Man (Scott Lang)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1608157385/mpq/antman4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'blue',
    power_three_color: 'yellow',
    feedees: 'Wasp (Hope Van Dyne)',
    feeders: 'Squirrel-Girl (Unbeatable)',
    char_level: 70,
  },
  {
    name: 'Ares (Dark Avengers)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1608158759/mpq/ares2.webp',
    rarity: 2,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'red',
    power_three_color: 'yellow',
    feedees: 'Ragnarok (Dark Avengers)',
    feeders: 'none',
    char_level: 15,
  },
  {
    name: 'Beast (Classic)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604172994/mpq/beast3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'green',
    power_three_color: 'yellow',
    feedees: 'Jean Grey (All New X-Men), Jubilee (Uncanny X-Men)',
    feeders: 'none',
    char_level: 40,
  },
  {
    name: 'Black Bolt (Inhuman King)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604172994/mpq/blockbolt5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'black',
    power_three_color: 'yellow',
    feedees: 'none',
    feeders: 'Medusa (Inhuman Queen)',
    char_level: 255,
  },
  {
    name: 'Black Panther (Civil War)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1608158759/mpq/blackpanther5.webp',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'yellow',
    power_three_color: 'red',
    feedees: 'Black Panther (King of Wakanda)',
    feeders: 'none',
    char_level: 255,
  },
  {
    name: 'Black Panther (King of Wakanda)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload//q_auto:eco/v1608158759/mpq/blackpanther4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'blue',
    power_three_color: 'red',
    feedees: 'Black Panther (Civil War)',
    feeders: "Black Panther (T'Challa)",
    char_level: 70,
  },
  {
    name: "Black Panther (T'Challa)",
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1608158759/mpq/blackpanther3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'blue',
    power_three_color: 'black',
    feedees: 'Black Panther (King of Wakanda)',
    feeders: 'none',
    char_level: 40,
  },
  {
    name: 'Black Widow (Natasha Romanoff)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604172995/mpq/blackwidow5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'red',
    power_three_color: 'black',
    feedees: 'none',
    feeders: 'Black Widow (Infinity War)',
    char_level: 255,
  },
  {
    name: 'Black Widow (Infinity War)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604172995/mpq/blackwidow4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'purple',
    power_three_color: 'yellow',
    feedees: 'Black Widow (Natasha Romanoff)',
    feeders: 'none',
    char_level: 70,
  },
  {
    name: 'Black Widow (Grey Suit)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604172995/mpq/blackwidow3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'green',
    power_three_color: 'red',
    feedees: 'Nick Fury (Director of S.H.I.E.L.D.),Black Widow (Infinity War)',
    feeders: 'Black Widow (Original)',
    char_level: 70,
  },
  {
    name: 'Black Widow (Original)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604172995/mpq/blackwidow2.png',
    rarity: 2,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'blue',
    power_three_color: 'black',
    feedees: 'Black Widow (Grey Suit)',
    feeders: 'none',
    char_level: 15,
  },
  {
    name: 'Blade (Modern)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604172994/mpq/blade4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'green',
    power_three_color: 'black',
    feedees: 'none',
    feeders: 'Blade (Daywalker)',
    char_level: 70,
  },
  {
    name: 'Blade (Daywalker)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604172993/mpq/blade3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'purple',
    power_three_color: 'green',
    feedees: 'Blade (Modern)',
    feedees: 'none',
    char_level: 40,
  },
  {
    name: 'Bullseye (Dark Avengers)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604172995/mpq/bullseye2.png',
    rarity: 2,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'black',
    power_three_color: 'green',
    feedees: 'Bullseye (Classic)',
    feedees: 'none',
    char_level: 15,
  },
  {
    name: 'Bullseye (Classic)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604172995/mpq/bullseye3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'black',
    power_three_color: 'green',
    feedees: 'Kingpin (Wilson Fisk)',
    feeders: 'Bullseye (Dark Avengers)',
    char_level: 40,
  },
  {
    name: 'Captain America (The First Avenger)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604172995/mpq/captainamerica5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'red',
    power_three_color: 'blue',
    feedees: 'none',
    feeders: 'Peggy Carter (Captain America)',
    char_level: 255,
  },
  {
    name: 'Captain America (Infinity War)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173002/mpq/infinitycap5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'purple',
    power_three_color: 'yellow',
    feedees: 'none',
    feeders: 'Captain America (Worthy)',
    char_level: 255,
  },
  {
    name: 'Captain America (Super Soldier)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604172995/mpq/captainamerica3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'red',
    power_three_color: 'blue',
    feedees: 'Captain America (Worthy), Winter Soldier (Bucky Barnes)',
    feeders: 'Captain America (Steve Rogers)',
    char_level: 40,
  },
  {
    name: 'Captain America (Steve Rogers)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604172995/mpq/captainamerica2.png',
    rarity: 2,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'red',
    power_three_color: 'blue',
    feedees: 'Captain America (Super Soldier)',
    feedees: 'none',
    char_level: 15,
  },
  {
    name: 'Captain Marvel (Galactic Warrior)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604181720/mpq/captainmarvel5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'green',
    power_three_color: 'yellow',
    feedees: 'none',
    feeders: 'Captain Marvel (Carol Danvers)',
    char_level: 255,
  },
  {
    name: 'Captain Marvel (Carol Danvers)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604172995/mpq/captainmarvel4.jpg',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'yellow',
    power_three_color: 'green',
    feedees: 'Captain Marvel (Galactic Warrior)',
    feeders: 'Captain Marvel (Modern)',
    char_level: 70,
  },
  {
    name: 'Captain Marvel (Modern)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604172995/mpq/captainmarvel3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'yellow',
    power_three_color: 'green',
    feedees: 'Captain Marvel (Carol Danvers),Talos (Skrull Warlord)',
    feeders: 'Captain Marvel (Ms. Marvel)',
    char_level: 40,
  },
  {
    name: 'Captain Marvel (Ms. Marvel)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604172995/mpq/captainmarvel2.png',
    rarity: 2,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'black',
    power_three_color: 'yellow',
    feedees: 'Captain Marvel (Modern)',
    feedees: 'none',
    char_level: 15,
  },
  {
    name: 'Carnage (Cletus Kassady)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1608156921/mpq/carnage4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'black',
    power_three_color: 'green',
    feedees: 'Doctor Octopus (Classic)',
    feeders: 'Doctor Octopus (Otto Octavius)',
    char_level: 70,
  },
  {
    name: 'Colossus (Classic)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604172996/mpq/colossus3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'red',
    power_three_color: 'black',
    feedees: 'Wolverine (X-Force), Magik (Classic)',
    feedees: 'none',
    char_level: 40,
  },
  {
    name: 'Cyclops (Classic)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1608074390/mpq/cyclops4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'yellow',
    power_three_color: 'blue',
    feedees: 'Cable (Nathan Summers)',
    feeders: 'Cyclops (Uncanny X-Men),Emma Frost (Astonishing X-Men)',
    char_level: 70,
  },
  {
    name: 'Cyclops (Uncanny X-Men)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604172996/mpq/cyclops3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'yellow',
    power_three_color: 'black',
    feeders: 'none',
    feedees: 'Cyclops (Classic)',
    char_level: 40,
  },
  {
    name: 'Daken (Dark Avengers)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604172996/mpq/daken2.png',
    rarity: 2,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'black',
    power_three_color: 'blue',
    feedees: 'Daken (Classic)',
    feedees: 'none',
    char_level: 15,
  },
  {
    name: 'Daken (Classic)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604172997/mpq/daken3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'purple',
    power_three_color: 'black',
    feedees: 'X-23 (All-New Wolverine)',
    feeders: 'Daken (Dark Avengers)',
    char_level: 40,
  },
  {
    name: 'Daredevil (Man Without Fear)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604172997/mpq/daredevil3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'blue',
    power_three_color: 'red',
    feeders: 'Elektra (Unkillable)',
    feedees: 'none',
    char_level: 40,
  },
  {
    name: 'Daredevil (Matt Murdock)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604172997/mpq/daredevil5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'purple',
    power_three_color: 'green',
    feedees: 'none',
    feeders: 'Kingpin (Wilson Fisk)',
    char_level: 255,
  },
  {
    name: "Deadpool (It's Me, Deadpool!)",
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604172997/mpq/deadpool3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'purple',
    power_three_color: 'black',
    feeders: 'Deadpool (Uncanny X-Force),Domino (X-Force)',
    feedees: 'none',
    char_level: 40,
  },
  {
    name: 'Deadpool (Uncanny X-Force)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604172997/mpq/deadpool4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'black',
    power_three_color: 'purple',
    feedees: 'none',
    feeders: "Deadpool (It's Me, Deadpool!)",
    char_level: 70,
  },
  {
    name: 'Doctor Doom (Classic)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604172998/mpq/docdoom3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'blue',
    power_three_color: 'purple',
    feedees: 'Invisible Woman (Classic)',
    feedees: 'none',
    char_level: 40,
  },
  {
    name: 'Doctor Octopus (Otto Octavius)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604172998/mpq/dococtopus3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'black',
    power_three_color: 'green',
    feedees: 'Carnage (Cletus Kassady), Sandman (Flint Marko)',
    feeders: 'none',
    char_level: 255,
  },
  {
    name: 'Doctor Octopus (Classic)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604172998/mpq/droctopus5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'blue',
    power_three_color: 'green',
    feedees: 'none',
    feeders: 'Carnage (Cletus Kassady)',
    char_level: 255,
  },
  {
    name: 'Doctor Strange (Stephen Strange)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604172998/mpq/drstrnage3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'purple',
    power_three_color: 'yellow',
    feedees: 'Nova (Sam Alexander), Mordo (Master of the Mystic Arts)',
    feeders: 'none',
    char_level: 40,
  },
  {
    name: 'Doctor Strange (Sorcerer Supreme)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604172998/mpq/drstrange5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'purple',
    power_three_color: 'yellow',
    feedees: 'none',
    feeders: 'Mordo (Master of the Mystic Arts)',
    char_level: 255,
  },
  {
    name: 'Drax (The Destroyer)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604172998/mpq/drax4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'purple',
    power_three_color: 'red',
    feedees: 'Star Lord (Awesome Mix Volume 2)',
    feeders: 'Rocket & Groot (Most Wanted)',
    char_level: 70,
  },
  {
    name: 'Elektra (Assassin)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604172999/mpq/elektra3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'black',
    power_three_color: 'red',
    feedees: 'Elektra (Unkillable)',
    feedees: 'none',
    char_level: 40,
  },
  {
    name: 'Elektra (Unkillable)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604172999/mpq/elektra4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'black',
    power_three_color: 'red',
    feedees: 'none',
    feeders: 'Daredevil (Man Without Fear)',
    char_level: 70,
  },
  {
    name: 'Gambit (Modern)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604182471/mpq/gambit3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'red',
    power_three_color: 'black',
    feedees: 'Rogue (Classic), Dazzler (Classic)',
    feeders: 'none',
    char_level: 40,
  },
  {
    name: 'Gamora (Guardians of the Galaxy)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604172999/mpq/gamora3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'red',
    power_three_color: 'black',
    feedees: 'Star-Lord (Legendary Outlaw),Gamora (Awesome Mix Volume 2)',
    feedees: 'none',
    char_level: 40,
  },
  {
    name: 'Gamora (Awesome Mix Volume 2)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604172999/mpq/gamora4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'black',
    power_three_color: 'blue',
    feedees: 'Thanos (The Mad Titan)',
    feedees: 'none',
    char_level: 70,
  },
  {
    name: 'Ghost Rider (Robbie Reyes)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1608085325/mpq/ghostrider5.webp',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'red',
    power_three_color: 'black',
    feedees: 'none',
    feeders: 'Ghost Rider (Johnny Blaze)',
    char_level: 255,
  },
  {
    name: 'Ghost Rider (Johnny Blaze)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1608085139/mpq/ghostrider4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'red',
    power_three_color: 'black',
    feedees: 'Ghost Rider (Robbie Reyes)',
    feeders: 'The Hood (Classic)',
    char_level: 70,
  },
  {
    name: 'Green Goblin (Norman Osborn)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173000/mpq/greengoblin5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'purple',
    power_three_color: 'yellow',
    feedees: 'none',
    feeders: 'Sandman (Flint Marko)',
    char_level: 255,
  },
  {
    name: 'Gwenpool (Gwen Poole)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1608158759/mpq/gwenpool4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'black',
    power_three_color: 'green',
    feedees: 'none',
    feeders: 'She-Hulk (Modern)',
    char_level: 70,
  },
  {
    name: 'Hawkeye (Clint Barton)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173001/mpq/hawkeye5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'blue',
    power_three_color: 'red',
    feedees: 'none',
    feeders: 'Kate Bishop (Hawkeye)',
    char_level: 255,
  },
  {
    name: 'Hawkeye (Hawkguy)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173001/mpq/hawkeye3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'blue',
    power_three_color: 'black',
    feedees: 'Kate Bishop (Hawkeye)',
    feeders: 'Hawkeye (Modern)',
    char_level: 15,
  },
  {
    name: 'Hawkeye (Modern)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173000/mpq/hawkeye2.png',
    rarity: 2,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'red',
    power_three_color: 'purple',
    feedees: 'Hawkeye (Hawkguy)',
    feeders: 'none',
    char_level: 15,
  },
  {
    name: 'Human Torch (Johnny Storm)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173002/mpq/humantorch2.png',
    rarity: 2,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'black',
    power_three_color: 'green',
    feedees: 'Human Torch (Classic)',
    feeders: 'none',
    char_level: 15,
  },
  {
    name: 'Human Torch (Classic)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173002/mpq/humantorch3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'black',
    power_three_color: 'green',
    feedees: 'The Thing (Classic), Human Torch (Jim Hammond)',
    feeders: '54',
    char_level: 40,
  },
  {
    name: 'The Hood (Classic)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173001/mpq/hood3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'blue',
    power_three_color: 'black',
    feedees: 'Ghost Rider (Johnny Blaze)',
    feeders: 'none',
    char_level: 40,
  },
  {
    name: 'The Hulk (Indestructible)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173001/mpq/hulk3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'black',
    power_three_color: 'green',
    feedees: 'The Hulk (Totally Awesome), The Hulk (Main Event)',
    feeders: 'Moonstone (Dark Avengers)',
    char_level: 40,
  },
  {
    name: 'The Hulk (Totally Awesome)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1608158335/mpq/chohulk4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'blue',
    power_three_color: 'black',
    feedees: 'The Hulk (Bruce Banner)',
    feeders: 'The Hulk (Indestructible)',
    char_level: 70,
  },
  {
    name: 'The Hulk (Main Event)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173001/mpq/hulk4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'purple',
    power_three_color: 'yellow',
    feedees: 'Loki (God of Mischief)',
    feeders: 'The Hulk (Indestructible)',
    char_level: 70,
  },
  {
    name: 'Iceman (All New X-Men)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173002/mpq/iceman4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'blue',
    power_three_color: 'purple',
    feedees: 'Iceman (Bobby Drake)',
    feeders: 'Mystique (Raven Darkholme)',
    char_level: 70,
  },
  {
    name: 'Invisible Woman (Classic)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173003/mpq/iw4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'blue',
    power_three_color: 'green',
    feedees: 'none',
    feeders: 'Doctor Doom (Classic)',
    char_level: 70,
  },
  {
    name: 'Iron Fist (Immortal Weapon)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173002/mpq/ironfist3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'purple',
    power_three_color: 'black',
    feedees: 'Iron Fist (Danny Rand)',
    feeders: 'none',
    char_level: 40,
  },
  {
    name: 'Iron Fist (Danny Rand)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173002/mpq/ironfist4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'green',
    power_three_color: 'black',
    feedees: 'none',
    feeders: 'Iron Fist (Immortal Weapon)',
    char_level: 70,
  },
  {
    name: 'Iron Man (Mark XLVI)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173003/mpq/ironman5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'red',
    power_three_color: 'blue',
    feedees: 'none',
    feeders: '133',
    char_level: 255,
  },
  {
    name: 'Iron Man (Model 40)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173003/mpq/ironman3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'blue',
    power_three_color: 'yellow',
    feedees: 'Iron Man (Hulkbuster), Riri Williams (Ironheart)',
    feeders: 'none',
    char_level: 40,
  },
  {
    name: 'Iron Man (Hulkbuster)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173001/mpq/hulkbuster4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'black',
    power_three_color: 'blue',
    feedees: 'Rescue (Pepper Potts)',
    feeders: 'Iron Man (Model 40)',
    char_level: 70,
  },
  {
    name: 'Jean Grey (Phoenix)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173008/mpq/phoenix5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'purple',
    power_three_color: 'red',
    feedees: 'none',
    feeders: 'Jubilee (Uncanny X-Men)',
    char_level: 255,
  },
  {
    name: 'Jean Grey (All New X-Men)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173003/mpq/jeangrey4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'purple',
    power_three_color: 'blue',
    feedees: 'none',
    feeders: 'Angel (All New X-Men), Beast (Classic)',
    char_level: 70,
  },
  {
    name: 'Jessica Jones (Alias Investigations)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173003/mpq/jessicajones5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'black',
    power_three_color: 'blue',
    feedees: 'none',
    feeders: 'America Chavez (Young Avengers)',
    char_level: 255,
  },
  {
    name: 'Jubilee (Uncanny X-Men)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload//q_auto:eco/v1608158759/mpq/jubilee4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'purple',
    power_three_color: 'green',
    feedees: 'Jean Grey (Phoenix)',
    feeders: 'none',
    char_level: 70,
  },
  {
    name: 'Kamala Khan (Ms. Marvel)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173007/mpq/msmarvel3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'purple',
    power_three_color: 'green',
    feedees: 'Medusa (Inhuman Queen), Lockjaw (Royal Bulldog)',
    feeders: 'none',
    char_level: 40,
  },
  {
    name: 'Kate Bishop (Hawkeye)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173004/mpq/katebishop4.jpg',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'black',
    power_three_color: 'purple',
    feedees: 'Hawkeye (Clint Barton)',
    feeders: 'Hawkeye (Hawkguy)',
    char_level: 70,
  },
  {
    name: 'Kingpin (Spider-Verse)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173004/mpq/kingpin5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'black',
    power_three_color: 'purple',
    feedees: 'none',
    feeders: 'Miles Morales (Spider-Man)',
    char_level: 255,
  },
  {
    name: 'Kingpin (Wilson Fisk)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173004/mpq/kingpin4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'purple',
    power_three_color: 'yellow',
    feedees: 'Daredevil (Matt Murdock)',
    feeders: 'Bullseye (Classic)',
    char_level: 70,
  },
  {
    name: 'Loki (God of Mischief)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173005/mpq/loki5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'green',
    power_three_color: 'black',
    feedees: 'none',
    feeders: 'The Hulk (Main Event)',
    char_level: 255,
  },
  {
    name: 'Loki (Dark Reign)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173005/mpq/loki3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'purple',
    power_three_color: 'green',
    feedees: 'Venom (Eddie Brock), Mysterio (Quentin Beck)',
    feeders: 'none',
    char_level: 40,
  },
  {
    name: 'Luke Cage (Hero For Hire)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173005/mpq/lukecage3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'red',
    power_three_color: 'black',
    feedees: 'Luke Cage (Power Man)',
    feeders: 'none',
    char_level: 40,
  },
  {
    name: 'Luke Cage (Power Man)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173005/mpq/lukecage4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'black',
    power_three_color: 'red',
    feedees: 'none',
    feeders: 'Luke Cage (Hero For Hire)',
    char_level: 70,
  },
  {
    name: 'Magneto (Marvel NOW!)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173006/mpq/magneto2.png',
    rarity: 2,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'purple',
    power_three_color: 'red',
    feedees: 'Magneto (Classic)',
    feeders: 'none',
    char_level: 15,
  },
  {
    name: 'Magneto (Classic)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173006/mpq/magneto3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'blue',
    power_three_color: 'yellow',
    feedees: 'Professor X (Charles Xavier),Juggernaut (Fear Itself)',
    feeders: 'Magneto (Marvel NOW!)',
    char_level: 40,
  },
  {
    name: 'Medusa (Inhuman Queen)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1608082512/medusa4_mjepk5.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'purple',
    power_three_color: 'green',
    feedees: 'Black Bolt (Inhuman King)',
    feeders: 'Medusa (Inhuman Queen)',
    char_level: 70,
  },
  {
    name: 'Miles Morales (Spider-Man)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173006/mpq/miles4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'yellow',
    power_three_color: 'red',
    feedees: 'Kingpin (Spiderverse)',
    feeders: 'Spider-Man (Classic)',
    char_level: 70,
  },
  {
    name: 'Moon Knight (Marc Spector)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173006/mpq/moonknight4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'purple',
    power_three_color: 'green',
    feedees: 'none',
    feeders: 'Sentry (Dark Avengers)',
    char_level: 70,
  },
  {
    name: 'Moonstone (Dark Avengers)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1608157652/mpq/moonstone2.webp',
    rarity: 2,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'black',
    power_three_color: 'red',
    feedees: 'The Hulk (Indestructible)',
    feeders: 'none',
    char_level: 15,
  },
  {
    name: 'Mordo (Master of the Mystic Arts)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173007/mpq/mordo4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'blue',
    power_three_color: 'purple',
    feedees: 'Doctor Strange (Sorcerer Supreme)',
    feeders: 'none',
    char_level: 70,
  },
  {
    name: 'Mr. Fantastic (Reed Richards)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173007/mpq/mrfantastic4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'yellow',
    power_three_color: 'black',
    feedees: 'Silver Surfer (Skyrider)',
    feeders: "Black Panther (T'Challa)",
    char_level: 70,
  },
  {
    name: 'Mystique (Raven Darkholme)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173007/mpq/mystique3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'blue',
    power_three_color: 'black',
    feedees: 'Iceman (All New X-Men)',
    feeders: 'none',
    char_level: 40,
  },
  {
    name: 'Nick Fury (Director of S.H.I.E.L.D.)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173007/mpq/nickfury4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'yellow',
    power_three_color: 'purple',
    feedees: 'none',
    feeders: 'Black Widow (Grey Suit)',
    char_level: 70,
  },
  {
    name: 'Nova (Sam Alexander)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173007/mpq/nova4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'yellow',
    power_three_color: 'black',
    feedees: 'none',
    feeders: 'Doctor Strange (Stephen Strange)',
    char_level: 70,
  },
  {
    name: 'Okoye (Warrior General)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173008/mpq/okoye4.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'yellow',
    power_three_color: 'red',
    feedees: 'none',
    feeders: 'Shuri (Master Engineer)',
    char_level: 255,
  },
  {
    name: 'Peggy Carter (Captain America)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173008/mpq/peggycarter4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'yellow',
    power_three_color: 'blue',
    feedees: 'Captain America (Super Soldier)',
    feeders: 'Psylocke (Classic)',
    char_level: 70,
  },
  {
    name: 'Professor X (Charles Xavier)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173008/mpq/profx4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'purple',
    power_three_color: 'yellow',
    feedees: 'Professor X (Classic)',
    feeders: 'Magneto (Classic)',
    char_level: 70,
  },
  {
    name: 'Psylocke (Classic)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1608076301/mpq/psylocke3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'blue',
    power_three_color: 'black',
    feedees: 'Peggy Carter (Captain America)',
    feeders: 'none',
    char_level: 40,
  },
  {
    name: 'The Punisher (Dark Reign)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173008/mpq/punisher3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'green',
    power_three_color: 'red',
    feedees: 'The Punisher (MAX)',
    feeders: 'none',
    char_level: 40,
  },
  {
    name: 'The Punisher (MAX)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173009/mpq/punisher4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'green',
    power_three_color: 'blue',
    feedees: 'none',
    feeders: 'The Punisher (Dark Reign)',
    char_level: 70,
  },
  {
    name: 'Quake (Daisy Johnson)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173009/mpq/quake4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'yellow',
    power_three_color: 'blue',
    feedees: 'none',
    feeders: 'Scarlet Witch (Wanda Maximoff)',
    char_level: 70,
  },
  {
    name: 'Quicksilver (Pietro Maximoff)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173009/mpq/quicksilver3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'blue',
    power_three_color: 'green',
    feedees: 'War Machine (James Rhodes)',
    feeders: 'none',
    char_level: 40,
  },
  {
    name: 'Ragnarok (Dark Avengers)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173009/mpq/raganrok3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'green',
    power_three_color: 'red',
    feedees: 'Valkyrie (Asgardian Warrior), X-23 (All-New Wolverine)',
    feeders: 'Ares (Dark Avengers)',
    char_level: 40,
  },
  {
    name: 'Red Hulk (Thunderbolt Ross)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173009/mpq/redhulk4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'green',
    power_three_color: 'purple',
    feedees: 'none',
    feeders: 'Thor (Modern)',
    char_level: 70,
  },
  {
    name: 'Rocket & Groot (Most Wanted)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173000/mpq/grocket3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'green',
    power_three_color: 'blue',
    feedees: 'Drax (The Destroyer), Rocket & Groot (Awesome Mix Volume 2)',
    feeders: 'none',
    char_level: 40,
  },
  {
    name: 'Rogue (Classic)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173010/mpq/rogue4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'red',
    power_three_color: 'yellow',
    feedees: 'Gambit (Classic)',
    feeders: 'Gambit (Modern)',
    char_level: 70,
  },
  {
    name: 'Sam Wilson (Falcon)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604172999/mpq/falcon3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'blue',
    power_three_color: 'purple',
    feedees: 'Sam Wilson (Captain America)',
    feeders: 'none',
    char_level: 40,
  },
  {
    name: 'Sam Wilson (Captain America)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173010/mpq/samwilson4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'blue',
    power_three_color: 'red',
    feedees: 'none',
    feeders: 'Sam Wilson (Falcon)',
    char_level: 70,
  },
  {
    name: 'Sandman (Flint Marko)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173010/mpq/sandman4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'purple',
    power_three_color: 'yellow',
    feedees: 'Green Goblin (Norman Osborn)',
    feeders: 'Doctor Octopus (Otto Octavius)',
    char_level: 70,
  },
  {
    name: 'Scarlet Witch (Wanda Maximoff)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173010/mpq/scarletwitch3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'green',
    power_three_color: 'blue',
    feedees: 'Quake (Daisy Johnson), Wiccan (Billy Kaplan)',
    feeders: 'none',
    char_level: 40,
  },
  {
    name: 'Sentry (Dark Avengers)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173010/mpq/sentry3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'green',
    power_three_color: 'yellow',
    feedees: 'Moon Knight (Marc Spector)',
    feeders: 'none',
    char_level: 40,
  },
  {
    name: 'She-Hulk (Modern)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173011/mpq/shehulk3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'green',
    power_three_color: 'red',
    feedees: 'Gwenpool (Gwen Poole)',
    feeders: 'none',
    char_level: 40,
  },
  {
    name: 'Shuri (Master Engineer)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173011/mpq/shuri4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'green',
    power_three_color: 'red',
    feedees: 'Okoye (Warrior General)',
    feeders: 'none',
    char_level: 70,
  },
  {
    name: 'Silver Surfer (Skyrider)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173011/mpq/silversurfer5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'red',
    power_three_color: 'black',
    feedees: 'none',
    feeders: 'Mr. Fantastic (Reed Richards)',
    char_level: 255,
  },
  {
    name: 'Spider-Man (Bag-Man)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173011/mpq/spiderman2.png',
    rarity: 2,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'blue',
    power_three_color: 'yellow',
    feedees: 'Spider-Man (Classic)',
    feeders: 'none',
    char_level: 15,
  },
  {
    name: 'Spider-Man (Back In Black)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604172994/mpq/bibsm5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'green',
    power_three_color: 'purple',
    feedees: 'none',
    feeders: 'Spider-Man (Classic)',
    char_level: 255,
  },
  {
    name: 'Spider-Man (Classic)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173011/mpq/spiderman3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'yellow',
    power_three_color: 'blue',
    feedees: 'Miles Morales (Spider-Man)',
    feeders: 'Spider-Man (Bag-Man)',
    char_level: 40,
  },
  {
    name: 'Spider-Man (Infinity War)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1608082675/mpq/mcuspiderman4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'green',
    power_three_color: 'red',
    feedees: 'Spider-Man (Back In Black)',
    feeders: 'none',
    char_level: 70,
  },
  {
    name: 'Spider-Man (Peter Parker)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1608083221/mpq/spiderman5.webp',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'green',
    power_three_color: 'red',
    feedees: 'none',
    feeders: 'Vulture (Adrian Toomes)',
    char_level: 255,
  },
  {
    name: 'Spider-Woman (Jessica Drew)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173012/mpq/spiderwoman4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'purple',
    power_three_color: 'red',
    feedees: 'none',
    feeders: 'Thanos (Modern)',
    char_level: 70,
  },
  {
    name: 'Squirrel-Girl (Unbeatable)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173012/mpq/squirrelgirl3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'purple',
    power_three_color: 'green',
    feedees: 'Ant-Man (Scott Lang), KravenThe Hunter (Sergei Kravinoff)',
    feeders: 'none',
    char_level: 40,
  },
  {
    name: 'Star-Lord (Awesome Mix Volume 2)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173012/mpq/starlord5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'purple',
    power_three_color: 'green',
    feedees: 'none',
    feeders: 'Drax (The Destroyer)',
    char_level: 255,
  },
  {
    name: 'Star-Lord (Legendary Outlaw)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173012/mpq/starlord4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'yellow',
    power_three_color: 'red',
    feedees: 'none',
    feeders: 'Star-Lord (Peter Quill), Gamora (Guardians of the Galaxy)',
    char_level: 70,
  },
  {
    name: 'Star-Lord (Peter Quill)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173012/mpq/starlord3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'yellow',
    power_three_color: 'red',
    feedees: 'Star-Lord (Legendary Outlaw)',
    feeders: 'none',
    char_level: 40,
  },
  {
    name: 'Storm (Classic)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604031220/mpq/Storm__28Classic_29.png',
    rarity: 2,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'blue',
    power_three_color: 'yellow',
    feedees: 'Storm (Mohawk)',
    feeders: 'none',
    char_level: 15,
  },
  {
    name: 'Storm (Mohawk)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload//q_auto:ecov1608158759/mpq/storm3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'yellow',
    power_three_color: 'black',
    feedees: 'Thor (Goddess of Thunder)',
    feeders: 'Storm (Classic)',
    char_level: 40,
  },
  {
    name: 'Thanos (The Mad Titan)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173013/mpq/thanos5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'purple',
    power_three_color: 'green',
    feedees: 'none',
    feeders: 'Gamora (Awesome Mix Volume 2)',
    char_level: 255,
  },
  {
    name: 'Thanos (Modern)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173013/mpq/thanos3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'purple',
    power_three_color: 'green',
    feedees: 'Spider-Woman (Jessica Drew), Thanos (Endgame)',
    feeders: 'none',
    char_level: 40,
  },
  {
    name: 'The Thing (Classic)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173013/mpq/thing4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'yellow',
    power_three_color: 'green',
    feedees: 'none',
    feeders: '55',
    char_level: 70,
  },
  {
    name: 'Thor (Goddess of Thunder)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173013/mpq/thor4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'yellow',
    power_three_color: 'blue',
    feedees: 'Storm (Ororo Munroe)',
    feeders: 'Storm (Mohawk)',
    char_level: 70,
  },
  {
    name: 'Thor (Marvel NOW!)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173013/mpq/thor2.png',
    rarity: 2,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'yellow',
    power_three_color: 'green',
    feedees: 'Thor (Modern)',
    feeders: 'none',
    char_level: 15,
  },
  {
    name: 'Thor (Modern)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173014/mpq/thor3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'yellow',
    power_three_color: 'green',
    feedees: 'Red Hulk (Thunderbolt Ross)',
    feeders: 'Thor (Marvel NOW!)',
    char_level: 40,
  },
  {
    name: 'Thor (Gladiator)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173014/mpq/thor5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'red',
    power_three_color: 'yellow',
    feedees: 'none',
    feeders: 'Valkyrie (Asgardian Warrior)',
    char_level: 255,
  },
  {
    name: 'Valkyrie (Asgardian Warrior)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173014/mpq/valkyrie4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'black',
    power_three_color: 'yellow',
    feedees: 'Thor (Gladiator)',
    feeders: 'Ragnarok (Dark Avengers)',
    char_level: 70,
  },
  {
    name: 'Venom (Eddie Brock)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173014/mpq/venom4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'black',
    power_three_color: 'yellow',
    feedees: 'none',
    feeders: 'Loki (Dark Reign)',
    char_level: 70,
  },
  {
    name: 'Vision (Android Avenger)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173014/mpq/vision3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'red',
    power_three_color: 'yellow',
    feedees: 'Wasp (Janet Vna Dyne)',
    feeders: 'none',
    char_level: 40,
  },
  {
    name: 'Vulture (Adrian Toomes)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173014/mpq/vulture4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'green',
    power_three_color: 'blue',
    feedees: 'Spider-Man (Peter Parker)',
    feeders: 'none',
    char_level: 70,
  },
  {
    name: 'War Machine (James Rhodes)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173015/mpq/warmachine4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'blue',
    power_three_color: 'green',
    feedees: 'Iron Man (Mark XLVI)',
    feeders: 'Quicksilver (Pietro Maximoff)',
    char_level: 70,
  },
  {
    name: 'Wasp (Hope Van Dyne)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1608157790/mpq/wasp5.webp',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'yellow',
    power_three_color: 'black',
    feedees: 'none',
    feeders: 'Ant Man (Scott Lang)',
    char_level: 255,
  },
  {
    name: 'Wasp (Janet Van Dyne)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1608157790/mpq/wasp4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'blue',
    power_three_color: 'black',
    feedees: 'none',
    feeders: 'Vision (Android Avenger)',
    char_level: 70,
  },
  {
    name: 'Winter Soldier (Bucky Barnes)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173015/mpq/wintersoldier4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'blue',
    power_three_color: 'red',
    feedees: 'Captain America (Infinity War)',
    feeders: 'Captain America (Super-Soldier)',
    char_level: 70,
  },
  {
    name: 'Wolverine (Astonishing X-Men)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173016/mpq/wolverine2.png',
    rarity: 2,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'red',
    power_three_color: 'yellow',
    feedees: 'Wolverine (Patch)',
    feeders: 'none',
    char_level: 15,
  },
  {
    name: 'Wolverine (Patch)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173016/mpq/wolverine3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'red',
    power_three_color: 'yellow',
    feedees: 'Wolverine (X-Force), Sabretooth (Victor Creed)',
    feeders: 'Wolverine (Astonishing X-Men)',
    char_level: 40,
  },
  {
    name: 'Wolverine (Old Man Logan)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173008/mpq/oldmanlogan5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'yellow',
    power_three_color: 'red',
    feedees: 'none',
    feeders: 'Wolverine (X-Force)',
    char_level: 255,
  },
  {
    name: 'Wolverine (X-Force)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1608082960/mpq/wolverine4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'black',
    power_three_color: 'yellow',
    feedees: 'Wolverine (Old Man Logan)',
    feeders: 'Colossus (Classic), Wolverine (Patch)',
    char_level: 70,
  },
  {
    name: 'X-23 (All-New Wolverine)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173017/mpq/x234.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'red',
    power_three_color: 'purple',
    feedees: 'none',
    feeders: 'Daken (Classic), X-23 (All-New Wolverine)',
    char_level: 70,
  },
  {
    name: 'Nightcrawler (Classic)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173007/mpq/nightcrawler4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'red',
    power_three_color: 'blue',
    feedees: 'Archangel (Classic)',
    feeders: 'Angel (All-New X-Men)',
    char_level: 70,
  },
  {
    name: 'Archangel (Classic)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1608158760/mpq/archangel5.webp',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'green',
    power_three_color: 'black',
    feedees: 'none',
    feeders: 'Nightcrawler (Classic)',
    char_level: 255,
  },
  {
    name: 'Captain America (Worthy)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173016/mpq/worthycap4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'red',
    power_three_color: 'yellow',
    feedees: 'none',
    feeders: 'Captain America (Super Soldier)',
    char_level: 70,
  },
  {
    name: 'Talos (Skrull Warlord)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173013/mpq/talos4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'blue',
    power_three_color: 'black',
    feedees: 'none',
    feeders: 'Captain Marvel (Modern)',
    char_level: 70,
  },
  {
    name: 'Magik (Classic)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173005/mpq/magik4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'red',
    power_three_color: 'blue',
    feedees: 'Hela (Goddess of Death)',
    feeders: 'Colossus (Classic)',
    char_level: 70,
  },
  {
    name: 'Hela (Goddess of Death)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173001/mpq/hela5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'green',
    power_three_color: 'black',
    feedees: 'none',
    feeders: 'Magik (Classic)',
    char_level: 255,
  },
  {
    name: 'Emma Frost (Astonishing X-Men)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604172999/mpq/emmafrost4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'black',
    power_three_color: 'yellow',
    feedees: 'Kitty Pryde (Uncanny X-Men)',
    feeders: 'Cyclops (Uncanny X-Men)',
    char_level: 70,
  },
  {
    name: 'Kitty Pryde (Uncanny X-Men)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173004/mpq/kittypryde5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'purple',
    power_three_color: 'red',
    feedees: 'none',
    feeders: 'Emma Frost (Astonishing X-Men)',
    char_level: 255,
  },
  {
    name: 'Domino (X-Force)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604172998/mpq/domino4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'red',
    power_three_color: 'black',
    feedees: 'none',
    feeders: "Deadpool (It's Me, Deadpool!)",
    char_level: 70,
  },
  {
    name: 'Dazzler (Classic)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604172997/mpq/dazzler4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'red',
    power_three_color: 'green',
    feedees: 'none',
    feeders: 'Gambit (Modern)',
    char_level: 70,
  },
  {
    name: 'The Hulk (Bruce Banner)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604172994/mpq/brucebanner5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'black',
    power_three_color: 'purple',
    feedees: 'none',
    feeders: 'The Hulk (Totally Awesome)',
    char_level: 255,
  },
  {
    name: 'Hawkeye (Ronin)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173010/mpq/ronin4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'red',
    power_three_color: 'purple',
    feedees: 'none',
    feeders: 'Hawkeye (Hawkguy)',
    char_level: 70,
  },
  {
    name: 'Human Torch (Jim Hammond)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173003/mpq/jimhammond4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'green',
    power_three_color: 'yellow',
    feedees: 'none',
    feeders: 'Human Torch (Classic)',
    char_level: 70,
  },
  {
    name: 'Riri Williams (Ironheart)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173003/mpq/ironheart4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'red',
    power_three_color: 'green',
    feedees: 'none',
    feeders: 'Iron Man (Model 40)',
    char_level: 70,
  },
  {
    name: 'Lockjaw (Royal Bulldog)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173005/mpq/lockjaw4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'blue',
    power_three_color: 'green',
    feedees: 'none',
    feeders: 'Kamala Khan (Ms. Marvel)',
    char_level: 70,
  },
  {
    name: 'Mysterio (Quentin Beck)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173007/mpq/mysterio4.jpg',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'blue',
    power_three_color: 'yellow',
    feedees: 'none',
    feeders: 'Loki (Dark Reign)',
    char_level: 70,
  },
  {
    name: 'Iceman (Bobby Drake)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173002/mpq/iceman5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'green',
    power_three_color: 'blue',
    feedees: 'none',
    feeders: 'Iceman (All-New X-Men)',
    char_level: 255,
  },
  {
    name: 'Doctor Doom (God Emperor)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604172998/mpq/docdoom5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'black',
    power_three_color: 'blue',
    feedees: 'none',
    feeders: 'Invisible Woman (Classic)',
    char_level: 255,
  },
  {
    name: 'Rescue (Pepper Potts)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173009/mpq/rescue5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'yellow',
    power_three_color: 'red',
    feedees: 'none',
    feeders: 'Iron Man (Hulkbuster)',
    char_level: 255,
  },
  {
    name: 'Professor X (Classic)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173008/mpq/profx5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'purple',
    power_three_color: 'black',
    feedees: 'none',
    feeders: 'Professor X (Charles Xavier)',
    char_level: 255,
  },
  {
    name: 'Gambit (Classic)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_aut0:eco/v1608157246/mpq/ganbit5.webp',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'red',
    power_three_color: 'black',
    feedees: 'none',
    feeders: 'Rogue (Classic)',
    char_level: 255,
  },
  {
    name: 'Storm (Ororo Munroe)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_aut0:ecov1608158759/mpq/storm5.webp',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'green',
    power_three_color: 'yellow',
    feedees: 'none',
    feeders: 'Thor (Goddess of Thunder)',
    char_level: 255,
  },
  {
    name: 'Juggernaut (Fear Itself)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1608083430/mpq/juggernaut5.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'red',
    power_three_color: 'blue',
    feedees: 'none',
    feeders: 'Magneto (Classic)',
    char_level: 70,
  },
  {
    name: 'Rocket & Groot (Awesome Mix Volume 2)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173000/mpq/grocket4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'green',
    power_three_color: 'blue',
    feedees: 'none',
    feeders: 'Rocket & Groot (Most Wanted)',
    char_level: 70,
  },
  {
    name: 'Wiccan (Billy Kaplan)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1608157480/mpq/wiccan4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'yellow',
    power_three_color: 'green',
    feedees: 'none',
    feeders: 'Scarlet Witch (Wanda Maximoff)',
    char_level: 70,
  },
  {
    name: 'Kraven The Hunter (Sergei Kravinoff)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1608076505/mpq/kraven4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'purple',
    power_three_color: 'blue',
    feedees: 'none',
    feeders: 'Squirrel-Girl (Unbeatable)',
    char_level: 70,
  },
  {
    name: 'Yondu (Awesome Mix Volume 2)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173016/mpq/yondu4.jpg',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'black',
    power_three_color: 'blue',
    feedees: 'none',
    feeders: 'Star Lord (Peter Quill)',
    char_level: 70,
  },
  {
    name: 'Thanos (Endgame)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1604173013/mpq/thanos4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'blue',
    power_three_color: 'green',
    feedees: 'none',
    feeders: 'Thanos (Modern)',
    char_level: 70,
  },
  {
    name: 'Sabretooth (Victor Creed)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/q_auto:eco/v1608157790/mpq/sabretooth4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'black',
    power_three_color: 'red',
    feedees: 'none',
    feeders: 'Wolverine (Patch)',
    char_level: 70,
  },
];
