export const seedDB = [
  {
    char_id: 1,
    name: 'America Chavez (Young Avengers)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172993/mpq/america4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'yellow',
    power_three_color: 'green',
    feedee_id: 'Jessica Jones (Alias Investigations)',
    feeder_id: 'none',
    char_level: 70,
  },
  {
    char_id: 2,
    name: 'Angel (All New X-Men)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172993/mpq/angel3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'black',
    power_three_color: 'green',
    feedee_id: 'Nightcrawler (Classic), Jean Grey (All New X-Men)',
    feeder_id: 'none',
    char_level: 40,
  },
  {
    char_id: 3,
    name: 'Ant-Man (Scott Lang)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172993/mpq/antman4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'blue',
    power_three_color: 'yellow',
    feedee_id: 'Squirrel-Girl (Unbeatable)',
    feeder_id: 'Wasp (Hope Van Dyne)',
    char_level: 70,
  },
  {
    char_id: 4,
    name: 'Ares (Dark Avengers)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172994/mpq/ares2.png',
    rarity: 2,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'red',
    power_three_color: 'yellow',
    feedee_id: 'Ragnarok (Dark Avengers)',
    feeder_id: 'none',
    char_level: 15,
  },
  {
    char_id: 5,
    name: 'Beast (Classic)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172994/mpq/beast3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'green',
    power_three_color: 'yellow',
    feedee_id: 'Jean Grey (All New X-Men), Jubilee (Uncanny X-Men)',
    feeder_id: 'none',
    char_level: 40,
  },
  {
    char_id: 6,
    name: 'Black Bolt (Inhuman King)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172994/mpq/blockbolt5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'black',
    power_three_color: 'yellow',
    feedee_id: 'none',
    feeder_id: 'Medusa (Inhuman Queen)',
    char_level: 255,
  },
  {
    char_id: 7,
    name: 'Black Panther (Civil War)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172994/mpq/blackpanther5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'yellow',
    power_three_color: 'red',
    feedee_id: 'Black Panther (King of Wakanda)',
    feeder_id: 'none',
    char_level: 255,
  },
  {
    char_id: 8,
    name: 'Black Panther (King of Wakanda)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172994/mpq/blackpanther4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'blue',
    power_three_color: 'red',
    feedee_id: 'Black Panther (Civil War)',
    feeder_id: "Black Panther (T'Challa)",
    char_level: 70,
  },
  {
    char_id: 9,
    name: "Black Panther (T'Challa)",
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172994/mpq/blackpanther3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'blue',
    power_three_color: 'black',
    feedee_id: 'Black Panther (King of Wakanda)',
    feedee_id: 'none',
    char_level: 40,
  },
  {
    char_id: 10,
    name: 'Black Widow (Natasha Romanoff)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172995/mpq/blackwidow5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'red',
    power_three_color: 'black',
    feedee_id: 'none',
    feeder_id: 'Black Widow (Infinity War)',
    char_level: 255,
  },
  {
    char_id: 11,
    name: 'Black Widow (Infinity War)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172995/mpq/blackwidow4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'purple',
    power_three_color: 'yellow',
    feedee_id: 'Black Widow (Natasha Romanoff)',
    feedee_id: 'none',
    char_level: 70,
  },
  {
    char_id: 12,
    name: 'Black Widow (Grey Suit)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172995/mpq/blackwidow3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'green',
    power_three_color: 'red',
    feedee_id:
      'Nick Fury (Director of S.H.I.E.L.D.),Black Widow (Infinity War)',
    feeder_id: 'Black Widow (Original)',
    char_level: 70,
  },
  {
    char_id: 13,
    name: 'Black Widow (Original)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172995/mpq/blackwidow2.png',
    rarity: 2,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'blue',
    power_three_color: 'black',
    feedee_id: 'Black Widow (Grey Suit)',
    feedee_id: 'none',
    char_level: 15,
  },
  {
    char_id: 14,
    name: 'Blade (Modern)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172994/mpq/blade4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'green',
    power_three_color: 'black',
    feedee_id: 'none',
    feeder_id: 'Blade (Daywalker)',
    char_level: 70,
  },
  {
    char_id: 15,
    name: 'Blade (Daywalker)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172993/mpq/blade3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'purple',
    power_three_color: 'green',
    feedee_id: 'Blade (Modern)',
    feedee_id: 'none',
    char_level: 40,
  },
  {
    char_id: 16,
    name: 'Bullseye (Dark Avengers)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172995/mpq/bullseye2.png',
    rarity: 2,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'black',
    power_three_color: 'green',
    feedee_id: 'Bullseye (Classic)',
    feedee_id: 'none',
    char_level: 15,
  },
  {
    char_id: 17,
    name: 'Bullseye (Classic)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172995/mpq/bullseye3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'black',
    power_three_color: 'green',
    feedee_id: 'Kingpin (Wilson Fisk)',
    feeder_id: 'Bullseye (Dark Avengers)',
    char_level: 40,
  },
  {
    char_id: 18,
    name: 'Captain America (The First Avenger)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172995/mpq/captainamerica5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'red',
    power_three_color: 'blue',
    feedee_id: 'none',
    feeder_id: 'Peggy Carter (Captain America)',
    char_level: 255,
  },
  {
    char_id: 19,
    name: 'Captain America (Infinity War)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173002/mpq/infinitycap5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'purple',
    power_three_color: 'yellow',
    feedee_id: 'none',
    feeder_id: 'Captain America (Worthy)',
    char_level: 255,
  },
  {
    char_id: 20,
    name: 'Captain America (Super Soldier)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172995/mpq/captainamerica3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'red',
    power_three_color: 'blue',
    feedee_id: 'Captain America (Worthy), Winter Soldier (Bucky Barnes)',
    feeder_id: 'Captain America (Steve Rogers)',
    char_level: 40,
  },
  {
    char_id: 21,
    name: 'Captain America (Steve Rogers)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172995/mpq/captainamerica2.png',
    rarity: 2,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'red',
    power_three_color: 'blue',
    feedee_id: 'Captain America (Super Soldier)',
    feedee_id: 'none',
    char_level: 15,
  },
  {
    char_id: 22,
    name: 'Captain Marvel (Galactic Warrior)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604181720/mpq/captainmarvel5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'green',
    power_three_color: 'yellow',
    feedee_id: 'none',
    feeder_id: 'Captain Marvel (Carol Danvers)',
    char_level: 255,
  },
  {
    char_id: 23,
    name: 'Captain Marvel (Carol Danvers)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172995/mpq/captainmarvel4.jpg',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'yellow',
    power_three_color: 'green',
    feedee_id: 'Captain Marvel (Galactic Warrior)',
    feeder_id: 'Captain Marvel (Modern)',
    char_level: 70,
  },
  {
    char_id: 24,
    name: 'Captain Marvel (Modern)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172995/mpq/captainmarvel3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'yellow',
    power_three_color: 'green',
    feedee_id: 'Captain Marvel (Carol Danvers),Talos (Skrull Warlord)',
    feeder_id: 'Captain Marvel (Ms. Marvel)',
    char_level: 40,
  },
  {
    char_id: 25,
    name: 'Captain Marvel (Ms. Marvel)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172995/mpq/captainmarvel2.png',
    rarity: 2,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'black',
    power_three_color: 'yellow',
    feedee_id: 'Captain Marvel (Modern)',
    feedee_id: 'none',
    char_level: 15,
  },
  {
    char_id: 26,
    name: 'Carnage (Cletus Kassady)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172996/mpq/carnage4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'black',
    power_three_color: 'green',
    feedee_id: 'Doctor Octopus (Classic)',
    feeder_id: 'Doctor Octopus (Otto Octavius)',
    char_level: 70,
  },
  {
    char_id: 27,
    name: 'Colossus (Classic)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172996/mpq/colossus3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'red',
    power_three_color: 'black',
    feedee_id: 'Wolverine (X-Force), Magik (Classic)',
    feedee_id: 'none',
    char_level: 40,
  },
  {
    char_id: 28,
    name: 'Cyclops (Classic)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172996/mpq/cyclops4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'yellow',
    power_three_color: 'blue',
    feedee_id: 'Cable (Nathan Summers)',
    feeder_id: 'Cyclops (Uncanny X-Men),Emma Frost (Astonishing X-Men)',
    char_level: 70,
  },
  {
    char_id: 29,
    name: 'Cyclops (Uncanny X-Men)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172996/mpq/cyclops3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'yellow',
    power_three_color: 'black',
    feeder_id: 'none',
    feedee_id: 'Cyclops (Classic)',
    char_level: 40,
  },
  {
    char_id: 30,
    name: 'Daken (Dark Avengers)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172996/mpq/daken2.png',
    rarity: 2,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'black',
    power_three_color: 'blue',
    feedee_id: 'Daken (Classic)',
    feedee_id: 'none',
    char_level: 15,
  },
  {
    char_id: 31,
    name: 'Daken (Classic)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172997/mpq/daken3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'yellow',
    power_three_color: 'black',
    feedee_id: 'X-23 (All-New Wolverine)',
    feeder_id: 'Daken (Dark Avengers)',
    char_level: 40,
  },
  {
    char_id: 32,
    name: 'Daredevil (Man Without Fear)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172997/mpq/daredevil3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'blue',
    power_three_color: 'red',
    feeder_id: 'Elektra (Unkillable)',
    feedee_id: 'none',
    char_level: 40,
  },
  {
    char_id: 33,
    name: 'Daredevil (Matt Murdock)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172997/mpq/daredevil5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'purple',
    power_three_color: 'green',
    feedee_id: 'none',
    feeder_id: 'Kingpin (Wilson Fisk)',
    char_level: 255,
  },
  {
    char_id: 34,
    name: "Deadpool (It's Me, Deadpool!)",
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172997/mpq/deadpool3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'purple',
    power_three_color: 'black',
    feeder_id: 'Deadpool (Uncanny X-Force),Domino (X-Force)',
    feedee_id: 'none',
    char_level: 40,
  },
  {
    char_id: 35,
    name: 'Deadpool (Uncanny X-Force)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172997/mpq/deadpool4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'black',
    power_three_color: 'purple',
    feedee_id: 'none',
    feeder_id: "Deadpool (It's Me, Deadpool!)",
    char_level: 70,
  },
  {
    char_id: 36,
    name: 'Doctor Doom (Classic)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172998/mpq/docdoom3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'blue',
    power_three_color: 'purple',
    feedee_id: 'Invisible Woman (Classic)',
    feedee_id: 'none',
    char_level: 40,
  },
  {
    char_id: 37,
    name: 'Doctor Octopus (Otto Octavius)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172998/mpq/dococtopus3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'black',
    power_three_color: 'green',
    feedee_id: 'Carnage (Cletus Kassady), Sandman (Flint Marko)',
    feeder_id: 'none',
    char_level: 255,
  },
  {
    char_id: 38,
    name: 'Doctor Octopus (Classic)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172998/mpq/droctopus5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'blue',
    power_three_color: 'green',
    feedee_id: 'none',
    feeder_id: 'Carnage (Cletus Kassady)',
    char_level: 255,
  },
  {
    char_id: 39,
    name: 'Doctor Strange (Stephen Strange)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172998/mpq/drstrnage3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'purple',
    power_three_color: 'yellow',
    feedee_id: 'Nova (Sam Alexander), Mordo (Master of the Mystic Arts)',
    feeder_id: 'none',
    char_level: 40,
  },
  {
    char_id: 40,
    name: 'Doctor Strange (Sorcerer Supreme)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172998/mpq/drstrange5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'purple',
    power_three_color: 'yellow',
    feedee_id: 'none',
    feeder_id: 'Mordo (Master of the Mystic Arts)',
    char_level: 255,
  },
  {
    char_id: 41,
    name: 'Drax (The Destroyer)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172998/mpq/drax4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'purple',
    power_three_color: 'red',
    feedee_id: 'Star Lord (Awesome Mix Volume 2)',
    feeder_id: 'Rocket & Groot (Most Wanted)',
    char_level: 70,
  },
  {
    char_id: 42,
    name: 'Elektra (Assassin)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172999/mpq/elektra3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'black',
    power_three_color: 'red',
    feedee_id: 'Elektra (Unkillable)',
    feedee_id: 'none',
    char_level: 40,
  },
  {
    char_id: 43,
    name: 'Elektra (Unkillable)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172999/mpq/elektra4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'black',
    power_three_color: 'red',
    feedee_id: 'none',
    feeder_id: 'Daredevil (Man Without Fear)',
    char_level: 70,
  },
  {
    char_id: 44,
    name: 'Gambit (Modern)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604182471/mpq/gambit3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'red',
    power_three_color: 'black',
    feedee_id: 'Rogue (Classic), Dazzler (Classic)',
    feeder_id: 'none',
    char_level: 40,
  },
  {
    char_id: 45,
    name: 'Gamora (Guardians of the Galaxy)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172999/mpq/gamora3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'red',
    power_three_color: 'black',
    feedee_id: 'Star-Lord (Legendary Outlaw),Gamora (Awesome Mix Volume 2)',
    feedee_id: 'none',
    char_level: 40,
  },
  {
    char_id: 46,
    name: 'Gamora (Awesome Mix Volume 2)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172999/mpq/gamora4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'black',
    power_three_color: 'blue',
    feedee_id: 'Thanos (The Mad Titan)',
    feedee_id: 'none',
    char_level: 70,
  },
  {
    char_id: 47,
    name: 'Ghost Rider (Robbie Reyes)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173000/mpq/ghostrider5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'red',
    power_three_color: 'black',
    feedee_id: 'none',
    feeder_id: 'Ghost Rider (Johnny Blaze)',
    char_level: 255,
  },
  {
    char_id: 48,
    name: 'Ghost Rider (Johnny Blaze)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173000/mpq/ghostrider4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'red',
    power_three_color: 'black',
    feedee_id: 'Ghost Rider (Robbie Reyes)',
    feeder_id: 'The Hood (Classic)',
    char_level: 70,
  },
  {
    char_id: 49,
    name: 'Green Goblin (Norman Osborn)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173000/mpq/greengoblin5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'purple',
    power_three_color: 'yellow',
    feedee_id: 'none',
    feeder_id: 'Sandman (Flint Marko)',
    char_level: 255,
  },
  {
    char_id: 50,
    name: 'Gwenpool (Gwen Poole)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173000/mpq/gwenpool4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'black',
    power_three_color: 'green',
    feedee_id: 'none',
    feeder_id: 'She-Hulk (Modern)',
    char_level: 70,
  },
  {
    char_id: 51,
    name: 'Hawkeye (Clint Barton)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173001/mpq/hawkeye5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'blue',
    power_three_color: 'red',
    feedee_id: 'none',
    feeder_id: 'Kate Bishop (Hawkeye)',
    char_level: 255,
  },
  {
    char_id: 52,
    name: 'Hawkeye (Hawkguy)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173001/mpq/hawkeye3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'blue',
    power_three_color: 'black',
    feedee_id: 'Kate Bishop (Hawkeye)',
    feeder_id: 'Hawkeye (Modern)',
    char_level: 15,
  },
  {
    char_id: 53,
    name: 'Hawkeye (Modern)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173000/mpq/hawkeye2.png',
    rarity: 2,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'red',
    power_three_color: 'purple',
    feedee_id: 'Hawkeye (Hawkguy)',
    feeder_id: 'none',
    char_level: 15,
  },
  {
    char_id: 54,
    name: 'Human Torch (Johnny Storm)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173002/mpq/humantorch2.png',
    rarity: 2,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'black',
    power_three_color: 'green',
    feedee_id: 'Human Torch (Classic)',
    feeder_id: 'none',
    char_level: 15,
  },
  {
    char_id: 55,
    name: 'Human Torch (Classic)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173002/mpq/humantorch3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'black',
    power_three_color: 'green',
    feedee_id: 'The Thing (Classic), Human Torch (Jim Hammond)',
    feeder_id: '54',
    char_level: 40,
  },
  {
    char_id: 56,
    name: 'The Hood (Classic)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173001/mpq/hood3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'blue',
    power_three_color: 'black',
    feedee_id: 'Ghost Rider (Johnny Blaze)',
    feeder_id: 'none',
    char_level: 40,
  },
  {
    char_id: 57,
    name: 'The Hulk (Indestructible)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173001/mpq/hulk3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'black',
    power_three_color: 'green',
    feedee_id: 'The Hulk (Totally Awesome), The Hulk (Main Event)',
    feeder_id: 'Moonstone (Dark Avengers)',
    char_level: 40,
  },
  {
    char_id: 58,
    name: 'The Hulk (Totally Awesome)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172996/mpq/chohulk4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'blue',
    power_three_color: 'black',
    feedee_id: 'The Hulk (Bruce Banner)',
    feeder_id: 'The Hulk (Indestructible)',
    char_level: 70,
  },
  {
    char_id: 59,
    name: 'The Hulk (Main Event)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173001/mpq/hulk4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'purple',
    power_three_color: 'yellow',
    feedee_id: 'Loki (God of Mischief)',
    feeder_id: 'The Hulk (Indestructible)',
    char_level: 70,
  },
  {
    char_id: 60,
    name: 'Iceman (All New X-Men)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173002/mpq/iceman4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'blue',
    power_three_color: 'purple',
    feedee_id: 'Iceman (Bobby Drake)',
    feeder_id: 'Mystique (Raven Darkholme)',
    char_level: 70,
  },
  {
    char_id: 61,
    name: 'Invisible Woman (Classic)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173003/mpq/iw4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'blue',
    power_three_color: 'green',
    feedee_id: 'none',
    feeder_id: 'Doctor Doom (Classic)',
    char_level: 70,
  },
  {
    char_id: 62,
    name: 'Iron Fist (Immortal Weapon)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173002/mpq/ironfist3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'purple',
    power_three_color: 'black',
    feedee_id: 'Iron Fist (Danny Rand)',
    feeder_id: 'none',
    char_level: 40,
  },
  {
    char_id: 63,
    name: 'Iron Fist (Danny Rand)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173002/mpq/ironfist4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'green',
    power_three_color: 'black',
    feedee_id: 'none',
    feeder_id: 'Iron Fist (Immortal Weapon)',
    char_level: 70,
  },
  {
    char_id: 64,
    name: 'Iron Man (Mark XLVI)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173003/mpq/ironman5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'red',
    power_three_color: 'blue',
    feedee_id: 'none',
    feeder_id: '133',
    char_level: 255,
  },
  {
    char_id: 65,
    name: 'Iron Man (Model 40)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173003/mpq/ironman3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'blue',
    power_three_color: 'yellow',
    feedee_id: 'Iron Man (Hulkbuster), Riri Williams (Ironheart)',
    feeder_id: 'none',
    char_level: 40,
  },
  {
    char_id: 66,
    name: 'Iron Man (Hulkbuster)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173001/mpq/hulkbuster4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'black',
    power_three_color: 'blue',
    feedee_id: 'Rescue (Pepper Potts)',
    feeder_id: 'Iron Man (Model 40)',
    char_level: 70,
  },
  {
    char_id: 67,
    name: 'Jean Grey (Phoenix)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173008/mpq/phoenix5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'purple',
    power_three_color: 'red',
    feedee_id: 'none',
    feeder_id: 'Jubilee (Uncanny X-Men)',
    char_level: 255,
  },
  {
    char_id: 68,
    name: 'Jean Grey (All New X-Men)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173003/mpq/jeangrey4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'purple',
    power_three_color: 'blue',
    feedee_id: 'none',
    feeder_id: 'Angel (All New X-Men), Beast (Classic)',
    char_level: 70,
  },
  {
    char_id: 69,
    name: 'Jessica Jones (Alias Investigations)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173003/mpq/jessicajones5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'black',
    power_three_color: 'blue',
    feedee_id: 'none',
    feeder_id: 'America Chavez (Young Avengers)',
    char_level: 255,
  },
  {
    char_id: 70,
    name: 'Jubilee (Uncanny X-Men)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173004/mpq/jubilee4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'purple',
    power_three_color: 'green',
    feedee_id: 'Jean Grey (Phoenix)',
    feeder_id: 'none',
    char_level: 70,
  },
  {
    char_id: 71,
    name: 'Kamala Khan (Ms. Marvel)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173007/mpq/msmarvel3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'purple',
    power_three_color: 'green',
    feedee_id: 'Medusa (Inhuman Queen), Lockjaw (Royal Bulldog)',
    feeder_id: 'none',
    char_level: 40,
  },
  {
    char_id: 72,
    name: 'Kate Bishop (Hawkeye)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173004/mpq/katebishop4.jpg',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'black',
    power_three_color: 'purple',
    feedee_id: 'Hawkeye (Clint Barton)',
    feeder_id: 'Hawkeye (Hawkguy)',
    char_level: 70,
  },
  {
    char_id: 73,
    name: 'Kingpin (Spider-Verse)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173004/mpq/kingpin5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'black',
    power_three_color: 'purple',
    feedee_id: 'none',
    feeder_id: 'Miles Morales (Spider-Man)',
    char_level: 255,
  },
  {
    char_id: 74,
    name: 'Kingpin (Wilson Fisk)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173004/mpq/kingpin4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'purple',
    power_three_color: 'yellow',
    feedee_id: 'Daredevil (Matt Murdock)',
    feeder_id: 'Bullseye (Classic)',
    char_level: 70,
  },
  {
    char_id: 75,
    name: 'Loki (God of Mischief)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173005/mpq/loki5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'green',
    power_three_color: 'black',
    feedee_id: 'none',
    feeder_id: 'The Hulk (Main Event)',
    char_level: 255,
  },
  {
    char_id: 76,
    name: 'Loki (Dark Reign)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173005/mpq/loki3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'purple',
    power_three_color: 'green',
    feedee_id: 'Venom (Eddie Brock), Mysterio (Quentin Beck)',
    feeder_id: 'none',
    char_level: 40,
  },
  {
    char_id: 77,
    name: 'Luke Cage (Hero For Hire)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173005/mpq/lukecage3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'red',
    power_three_color: 'black',
    feedee_id: 'Luke Cage (Power Man)',
    feeder_id: 'none',
    char_level: 40,
  },
  {
    char_id: 78,
    name: 'Luke Cage (Power Man)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173005/mpq/lukecage4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'black',
    power_three_color: 'red',
    feedee_id: 'none',
    feeder_id: 'Luke Cage (Hero For Hire)',
    char_level: 70,
  },
  {
    char_id: 79,
    name: 'Magneto (Marvel NOW!)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173006/mpq/magneto2.png',
    rarity: 2,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'purple',
    power_three_color: 'red',
    feedee_id: 'Magneto (Classic)',
    feeder_id: 'none',
    char_level: 15,
  },
  {
    char_id: 80,
    name: 'Magneto (Classic)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173006/mpq/magneto3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'blue',
    power_three_color: 'yellow',
    feedee_id: 'Professor X (Charles Xavier),Juggernaut (Fear Itself)',
    feeder_id: 'Magneto (Marvel NOW!)',
    char_level: 40,
  },
  {
    char_id: 81,
    name: 'Medusa (Inhuman Queen)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173006/mpq/medusa4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'purple',
    power_three_color: 'green',
    feedee_id: 'Black Bolt (Inhuman King)',
    feeder_id: 'Medusa (Inhuman Queen)',
    char_level: 70,
  },
  {
    char_id: 82,
    name: 'Miles Morales (Spider-Man)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173006/mpq/miles4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'yellow',
    power_three_color: 'red',
    feedee_id: 'Kingpin (Spiderverse)',
    feeder_id: 'Spider-Man (Classic)',
    char_level: 70,
  },
  {
    char_id: 83,
    name: 'Moon Knight (Marc Spector)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173006/mpq/moonknight4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'purple',
    power_three_color: 'green',
    feedee_id: 'none',
    feeder_id: 'Sentry (Dark Avengers)',
    char_level: 70,
  },
  {
    char_id: 84,
    name: 'Moonstone (Dark Avengers)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173007/mpq/moonstone2.png',
    rarity: 2,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'black',
    power_three_color: 'red',
    feedee_id: 'The Hulk (Indestructible)',
    feeder_id: 'none',
    char_level: 15,
  },
  {
    char_id: 85,
    name: 'Mordo (Master of the Mystic Arts)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173007/mpq/mordo4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'blue',
    power_three_color: 'purple',
    feedee_id: 'Doctor Strange (Sorcerer Supreme)',
    feeder_id: 'none',
    char_level: 70,
  },
  {
    char_id: 86,
    name: 'Mr. Fantastic (Reed Richards)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173007/mpq/mrfantastic4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'yellow',
    power_three_color: 'black',
    feedee_id: 'Silver Surfer (Skyrider)',
    feeder_id: "Black Panther (T'Challa)",
    char_level: 70,
  },
  {
    char_id: 87,
    name: 'Mystique (Raven Darkholme)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173007/mpq/mystique3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'blue',
    power_three_color: 'black',
    feedee_id: 'Iceman (All New X-Men)',
    feeder_id: 'none',
    char_level: 40,
  },
  {
    char_id: 88,
    name: 'Nick Fury (Director of S.H.I.E.L.D.)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173007/mpq/nickfury4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'yellow',
    power_three_color: 'purple',
    feedee_id: 'none',
    feeder_id: 'Black Widow (Grey Suit)',
    char_level: 70,
  },
  {
    char_id: 89,
    name: 'Nova (Sam Alexander)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173007/mpq/nova4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'yellow',
    power_three_color: 'black',
    feedee_id: 'none',
    feeder_id: 'Doctor Strange (Stephen Strange)',
    char_level: 70,
  },
  {
    char_id: 90,
    name: 'Okoye (Warrior General)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173008/mpq/okoye4.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'yellow',
    power_three_color: 'red',
    feedee_id: 'none',
    feeder_id: 'Shuri (Master Engineer)',
    char_level: 255,
  },
  {
    char_id: 91,
    name: 'Peggy Carter (Captain America)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173008/mpq/peggycarter4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'yellow',
    power_three_color: 'blue',
    feedee_id: 'Captain America (Super Soldier)',
    feeder_id: 'Psylocke (Classic)',
    char_level: 70,
  },
  {
    char_id: 92,
    name: 'Professor X (Charles Xavier)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173008/mpq/profx4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'purple',
    power_three_color: 'yellow',
    feedee_id: 'Professor X (Classic)',
    feeder_id: 'Magneto (Classic)',
    char_level: 70,
  },
  {
    char_id: 93,
    name: 'Psylocke (Classic)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173009/mpq/psylocke3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'blue',
    power_three_color: 'black',
    feedee_id: 'Peggy Carter (Captain America)',
    feeder_id: 'none',
    char_level: 40,
  },
  {
    char_id: 94,
    name: 'The Punisher (Dark Reign)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173008/mpq/punisher3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'green',
    power_three_color: 'red',
    feedee_id: 'The Punisher (MAX)',
    feeder_id: 'none',
    char_level: 40,
  },
  {
    char_id: 95,
    name: 'The Punisher (MAX)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173009/mpq/punisher4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'green',
    power_three_color: 'blue',
    feedee_id: 'none',
    feeder_id: 'The Punisher (Dark Reign)',
    char_level: 70,
  },
  {
    char_id: 96,
    name: 'Quake (Daisy Johnson)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173009/mpq/quake4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'yellow',
    power_three_color: 'blue',
    feedee_id: 'none',
    feeder_id: 'Scarlet Witch (Wanda Maximoff)',
    char_level: 70,
  },
  {
    char_id: 97,
    name: 'Quicksilver (Pietro Maximoff)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173009/mpq/quicksilver3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'blue',
    power_three_color: 'green',
    feedee_id: 'War Machine (James Rhodes)',
    feeder_id: 'none',
    char_level: 40,
  },
  {
    char_id: 98,
    name: 'Ragnarok (Dark Avengers)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173009/mpq/raganrok3.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'green',
    power_three_color: 'red',
    feedee_id: 'Valkyrie (Asgardian Warrior), X-23 (All-New Wolverine)',
    feeder_id: 'Ares (Dark Avengers)',
    char_level: 40,
  },
  {
    char_id: 99,
    name: 'Red Hulk (Thunderbolt Ross)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173009/mpq/redhulk4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'green',
    power_three_color: 'purple',
    feedee_id: 'none',
    feeder_id: 'Thor (Modern)',
    char_level: 70,
  },
  {
    char_id: 100,
    name: 'Rocket & Groot (Most Wanted)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173000/mpq/grocket3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'green',
    power_three_color: 'blue',
    feedee_id: 'Drax (The Destroyer), Rocket & Groot (Awesome Mix Volume 2)',
    feeder_id: 'none',
    char_level: 40,
  },
  {
    char_id: 101,
    name: 'Rogue (Classic)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173010/mpq/rogue4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'red',
    power_three_color: 'yellow',
    feedee_id: 'Gambit (Classic)',
    feeder_id: 'Gambit (Modern)',
    char_level: 70,
  },
  {
    char_id: 102,
    name: 'Sam Wilson (Falcon)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172999/mpq/falcon3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'blue',
    power_three_color: 'purple',
    feedee_id: 'Sam Wilson (Captain America)',
    feeder_id: 'none',
    char_level: 40,
  },
  {
    char_id: 103,
    name: 'Sam Wilson (Captain America)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173010/mpq/samwilson4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'blue',
    power_three_color: 'red',
    feedee_id: 'none',
    feeder_id: 'Sam Wilson (Falcon)',
    char_level: 70,
  },
  {
    char_id: 104,
    name: 'Sandman (Flint Marko)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173010/mpq/sandman4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'purple',
    power_three_color: 'yellow',
    feedee_id: 'Green Goblin (Norman Osborn)',
    feeder_id: 'Doctor Octopus (Otto Octavius)',
    char_level: 70,
  },
  {
    char_id: 105,
    name: 'Scarlet Witch (Wanda Maximoff)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173010/mpq/scarletwitch3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'green',
    power_three_color: 'blue',
    feedee_id: 'Quake (Daisy Johnson), Wiccan (Billy Kaplan)',
    feeder_id: 'none',
    char_level: 40,
  },
  {
    char_id: 106,
    name: 'Sentry (Dark Avengers)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173010/mpq/sentry3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'green',
    power_three_color: 'yellow',
    feedee_id: 'Moon Knight (Marc Spector)',
    feeder_id: 'none',
    char_level: 40,
  },
  {
    char_id: 107,
    name: 'She-Hulk (Modern)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173011/mpq/shehulk3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'green',
    power_three_color: 'red',
    feedee_id: 'Gwenpool (Gwen Poole)',
    feeder_id: 'none',
    char_level: 40,
  },
  {
    char_id: 108,
    name: 'Shuri (Master Engineer)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173011/mpq/shuri4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'green',
    power_three_color: 'red',
    feedee_id: 'Okoye (Warrior General)',
    feeder_id: 'none',
    char_level: 70,
  },
  {
    char_id: 109,
    name: 'Silver Surfer (Skyrider)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173011/mpq/silversurfer5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'red',
    power_three_color: 'black',
    feedee_id: 'none',
    feeder_id: 'Mr. Fantastic (Reed Richards)',
    char_level: 255,
  },
  {
    char_id: 110,
    name: 'Spider-Man (Bag-Man)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173011/mpq/spiderman2.png',
    rarity: 2,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'blue',
    power_three_color: 'yellow',
    feedee_id: 'Spider-Man (Classic)',
    feeder_id: 'none',
    char_level: 15,
  },
  {
    char_id: 111,
    name: 'Spider-Man (Back In Black)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172994/mpq/bibsm5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'green',
    power_three_color: 'purple',
    feedee_id: 'none',
    feeder_id: 'Spider-Man (Classic)',
    char_level: 255,
  },
  {
    char_id: 112,
    name: 'Spider-Man (Classic)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173011/mpq/spiderman3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'yellow',
    power_three_color: 'blue',
    feedee_id: 'Miles Morales (Spider-Man)',
    feeder_id: 'Spider-Man (Bag-Man)',
    char_level: 40,
  },
  {
    char_id: 113,
    name: 'Spider-Man (Infinity War)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173006/mpq/mcuspiderman4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'green',
    power_three_color: 'red',
    feedee_id: 'Spider-Man (Infinity War)',
    feeder_id: 'none',
    char_level: 70,
  },
  {
    char_id: 114,
    name: 'Spider-Man (Peter Parker)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173012/mpq/spiderman5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'green',
    power_three_color: 'red',
    feedee_id: 'none',
    feeder_id: 'Vulture (Adrian Toomes)',
    char_level: 255,
  },
  {
    char_id: 115,
    name: 'Spider-Woman (Jessica Drew)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173012/mpq/spiderwoman4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'purple',
    power_three_color: 'red',
    feedee_id: 'none',
    feeder_id: 'Thanos (Modern)',
    char_level: 70,
  },
  {
    char_id: 116,
    name: 'Squirrel-Girl (Unbeatable)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173012/mpq/squirrelgirl3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'purple',
    power_three_color: 'green',
    feedee_id: 'Ant-Man (Scott Lang), KravenThe Hunter (Sergei Kravinoff)',
    feeder_id: 'none',
    char_level: 40,
  },
  {
    char_id: 117,
    name: 'Star-Lord (Awesome Mix Volume 2)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173012/mpq/starlord5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'purple',
    power_three_color: 'green',
    feedee_id: 'none',
    feeder_id: 'Drax (The Destroyer)',
    char_level: 255,
  },
  {
    char_id: 118,
    name: 'Star-Lord (Legendary Outlaw)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173012/mpq/starlord4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'yellow',
    power_three_color: 'red',
    feedee_id: 'none',
    feeder_id: 'Star-Lord (Peter Quill), Gamora (Guardians of the Galaxy)',
    char_level: 70,
  },
  {
    char_id: 119,
    name: 'Star-Lord (Peter Quill)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173012/mpq/starlord3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'yellow',
    power_three_color: 'red',
    feedee_id: 'Star-Lord (Legendary Outlaw)',
    feeder_id: 'none',
    char_level: 40,
  },
  {
    char_id: 120,
    name: 'Storm (Classic)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604031220/mpq/Storm__28Classic_29.png',
    rarity: 2,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'blue',
    power_three_color: 'yellow',
    feedee_id: 'Storm (Mohawk)',
    feeder_id: 'none',
    char_level: 15,
  },
  {
    char_id: 121,
    name: 'Storm (Mohawk)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173012/mpq/storm5.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'yellow',
    power_three_color: 'black',
    feedee_id: 'Thor (Goddess of Thunder)',
    feeder_id: 'Storm (Classic)',
    char_level: 40,
  },
  {
    char_id: 122,
    name: 'Thanos (The Mad Titan)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173013/mpq/thanos5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'purple',
    power_three_color: 'green',
    feedee_id: 'none',
    feeder_id: 'Gamora (Awesome Mix Volume 2)',
    char_level: 255,
  },
  {
    char_id: 123,
    name: 'Thanos (Modern)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173013/mpq/thanos3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'purple',
    power_three_color: 'green',
    feedee_id: 'Spider-Woman (Jessica Drew), Thanos (Endgame)',
    feeder_id: 'none',
    char_level: 40,
  },
  {
    char_id: 124,
    name: 'The Thing (Classic)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173013/mpq/thing4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'yellow',
    power_three_color: 'green',
    feedee_id: 'none',
    feeder_id: '55',
    char_level: 70,
  },
  {
    char_id: 125,
    name: 'Thor (Goddess of Thunder)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173013/mpq/thor4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'yellow',
    power_three_color: 'blue',
    feedee_id: 'Storm (Ororo Munroe)',
    feeder_id: 'Storm (Mohawk)',
    char_level: 70,
  },
  {
    char_id: 126,
    name: 'Thor (Marvel NOW!)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173013/mpq/thor2.png',
    rarity: 2,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'yellow',
    power_three_color: 'green',
    feedee_id: 'Thor (Modern)',
    feeder_id: 'none',
    char_level: 15,
  },
  {
    char_id: 127,
    name: 'Thor (Modern)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173014/mpq/thor3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'yellow',
    power_three_color: 'green',
    feedee_id: 'Red Hulk (Thunderbolt Ross)',
    feeder_id: 'Thor (Marvel NOW!)',
    char_level: 40,
  },
  {
    char_id: 128,
    name: 'Thor (Gladiator)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173014/mpq/thor5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'red',
    power_three_color: 'yellow',
    feedee_id: 'none',
    feeder_id: 'Valkyrie (Asgardian Warrior)',
    char_level: 255,
  },
  {
    char_id: 129,
    name: 'Valkyrie (Asgardian Warrior)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173014/mpq/valkyrie4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'black',
    power_three_color: 'yellow',
    feedee_id: 'Thor (Gladiator)',
    feeder_id: 'Ragnarok (Dark Avengers)',
    char_level: 70,
  },
  {
    char_id: 130,
    name: 'Venom (Eddie Brock)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173014/mpq/venom4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'black',
    power_three_color: 'yellow',
    feedee_id: 'none',
    feeder_id: 'Loki (Dark Reign)',
    char_level: 70,
  },
  {
    char_id: 131,
    name: 'Vision (Android Avenger)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173014/mpq/vision3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'red',
    power_three_color: 'yellow',
    feedee_id: 'Wasp (Janet Vna Dyne)',
    feeder_id: 'none',
    char_level: 40,
  },
  {
    char_id: 132,
    name: 'Vulture (Adrian Toomes)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173014/mpq/vulture4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'green',
    power_three_color: 'blue',
    feedee_id: 'Spider-Man (Peter Parker)',
    feeder_id: 'none',
    char_level: 70,
  },
  {
    char_id: 133,
    name: 'War Machine (James Rhodes)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173015/mpq/warmachine4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'blue',
    power_three_color: 'green',
    feedee_id: 'Iron Man (Mark XLVI)',
    feeder_id: 'Quicksilver (Pietro Maximoff)',
    char_level: 70,
  },
  {
    char_id: 134,
    name: 'Wasp (Hope Van Dyne)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173015/mpq/wasp5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'yellow',
    power_three_color: 'black',
    feedee_id: 'none',
    feeder_id: 'Ant Man (Scott Lang)',
    char_level: 255,
  },
  {
    char_id: 135,
    name: 'Wasp (Janet Van Dyne)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173015/mpq/wasp4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'blue',
    power_three_color: 'black',
    feedee_id: 'none',
    feeder_id: 'Vision (Android Avenger)',
    char_level: 70,
  },
  {
    char_id: 136,
    name: 'Winter Soldier (Bucky Barnes)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173015/mpq/wintersoldier4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'blue',
    power_three_color: 'red',
    feedee_id: 'Captain America (Infinity War)',
    feeder_id: 'Captain America (Super-Soldier)',
    char_level: 70,
  },
  {
    char_id: 137,
    name: 'Wolverine (Astonishing X-Men)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173016/mpq/wolverine2.png',
    rarity: 2,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'red',
    power_three_color: 'yellow',
    feedee_id: 'Wolverine (Patch)',
    feeder_id: 'none',
    char_level: 15,
  },
  {
    char_id: 138,
    name: 'Wolverine (Patch)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173016/mpq/wolverine3.png',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'red',
    power_three_color: 'yellow',
    feedee_id: 'Wolverine (X-Force), Sabretooth (Victor Creed)',
    feeder_id: 'Wolverine (Astonishing X-Men)',
    char_level: 40,
  },
  {
    char_id: 139,
    name: 'Wolverine (Old Man Logan)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173008/mpq/oldmanlogan5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'yellow',
    power_three_color: 'red',
    feedee_id: 'none',
    feeder_id: 'Wolverine (X-Force)',
    char_level: 255,
  },
  {
    char_id: 140,
    name: 'Wolverine (X-Force)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173016/mpq/wolverine4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'black',
    power_three_color: 'yellow',
    feedee_id: 'Wolverine (Old Man Logan)',
    feeder_id: 'Colossus (Classic), Wolverine (Patch)',
    char_level: 70,
  },
  {
    char_id: 141,
    name: 'X-23 (All-New Wolverine)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173017/mpq/x234.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'red',
    power_three_color: 'purple',
    feedee_id: 'none',
    feeder_id: 'Daken (Classic), X-23 (All-New Wolverine)',
    char_level: 70,
  },
  {
    char_id: 142,
    name: 'Nightcrawler (Classic)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173007/mpq/nightcrawler4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'red',
    power_three_color: 'blue',
    feedee_id: 'Archangel (Classic)',
    feeder_id: 'Angel (All-New X-Men)',
    char_level: 70,
  },
  {
    char_id: 143,
    name: 'Archangel (Classic)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172993/mpq/archangel5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'green',
    power_three_color: 'black',
    feedee_id: 'none',
    feeder_id: 'Nightcrawler (Classic)',
    char_level: 255,
  },
  {
    char_id: 144,
    name: 'Captain America (Worthy)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173016/mpq/worthycap4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'red',
    power_three_color: 'yellow',
    feedee_id: 'none',
    feeder_id: 'Captain America (Super Soldier)',
    char_level: 70,
  },
  {
    char_id: 145,
    name: 'Talos (Skrull Warlord)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173013/mpq/talos4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'blue',
    power_three_color: 'black',
    feedee_id: 'none',
    feeder_id: 'Captain Marvel (Modern)',
    char_level: 70,
  },
  {
    char_id: 146,
    name: 'Magik (Classic)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173005/mpq/magik4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'red',
    power_three_color: 'blue',
    feedee_id: 'Hela (Goddess of Death)',
    feeder_id: 'Colossus (Classic)',
    char_level: 70,
  },
  {
    char_id: 147,
    name: 'Hela (Goddess of Death)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173001/mpq/hela5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'green',
    power_three_color: 'black',
    feedee_id: 'none',
    feeder_id: 'Magik (Classic)',
    char_level: 255,
  },
  {
    char_id: 148,
    name: 'Emma Frost (Astonishing X-Men)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172999/mpq/emmafrost4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'black',
    power_three_color: 'yellow',
    feedee_id: 'Kitty Pryde (Uncanny X-Men)',
    feeder_id: 'Cyclops (Uncanny X-Men)',
    char_level: 70,
  },
  {
    char_id: 149,
    name: 'Kitty Pryde (Uncanny X-Men)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173004/mpq/kittypryde5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'purple',
    power_three_color: 'red',
    feedee_id: 'none',
    feeder_id: 'Emma Frost (Astonishing X-Men)',
    char_level: 255,
  },
  {
    char_id: 150,
    name: 'Domino (X-Force)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172998/mpq/domino4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'red',
    power_three_color: 'black',
    feedee_id: 'none',
    feeder_id: "Deadpool (It's Me, Deadpool!)",
    char_level: 70,
  },
  {
    char_id: 151,
    name: 'Dazzler (Classic)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172997/mpq/dazzler4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'red',
    power_three_color: 'green',
    feedee_id: 'none',
    feeder_id: 'Gambit (Modern)',
    char_level: 70,
  },
  {
    char_id: 152,
    name: 'The Hulk (Bruce Banner)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172994/mpq/brucebanner5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'black',
    power_three_color: 'purple',
    feedee_id: 'none',
    feeder_id: 'The Hulk (Totally Awesome)',
    char_level: 255,
  },
  {
    char_id: 153,
    name: 'Hawkeye (Ronin)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173010/mpq/ronin4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'red',
    power_three_color: 'purple',
    feedee_id: 'none',
    feeder_id: 'Hawkeye (Hawkguy)',
    char_level: 70,
  },
  {
    char_id: 154,
    name: 'Human Torch (Jim Hammond)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173003/mpq/jimhammond4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'green',
    power_three_color: 'yellow',
    feedee_id: 'none',
    feeder_id: 'Human Torch (Classic)',
    char_level: 70,
  },
  {
    char_id: 155,
    name: 'Riri Williams (Ironheart)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173003/mpq/ironheart4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'red',
    power_three_color: 'green',
    feedee_id: 'none',
    feeder_id: 'Iron Man (Model 40)',
    char_level: 70,
  },
  {
    char_id: 156,
    name: 'Lockjaw (Royal Bulldog)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173005/mpq/lockjaw4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'blue',
    power_three_color: 'green',
    feedee_id: 'none',
    feeder_id: 'Kamala Khan (Ms. Marvel)',
    char_level: 70,
  },
  {
    char_id: 157,
    name: 'Mysterio (Quentin Beck)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173007/mpq/mysterio4.jpg',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'blue',
    power_three_color: 'yellow',
    feedee_id: 'none',
    feeder_id: 'Loki (Dark Reign)',
    char_level: 70,
  },
  {
    char_id: 158,
    name: 'Iceman (Bobby Drake)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173002/mpq/iceman5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'green',
    power_three_color: 'blue',
    feedee_id: 'none',
    feeder_id: 'Iceman (All-New X-Men)',
    char_level: 255,
  },
  {
    char_id: 159,
    name: 'Doctor Doom (God Emperor)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604172998/mpq/docdoom5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'black',
    power_three_color: 'blue',
    feedee_id: 'none',
    feeder_id: 'Invisible Woman (Classic)',
    char_level: 255,
  },
  {
    char_id: 160,
    name: 'Rescue (Pepper Potts)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173009/mpq/rescue5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'yellow',
    power_three_color: 'red',
    feedee_id: 'none',
    feeder_id: 'Iron Man (Hulkbuster)',
    char_level: 255,
  },
  {
    char_id: 161,
    name: 'Professor X (Classic)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173008/mpq/profx5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'purple',
    power_three_color: 'black',
    feedee_id: 'none',
    feeder_id: 'Professor X (Charles Xavier)',
    char_level: 255,
  },
  {
    char_id: 162,
    name: 'Gambit (Classic)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173000/mpq/ganbit5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'red',
    power_three_color: 'black',
    feedee_id: 'none',
    feeder_id: 'Rogue (Classic)',
    char_level: 255,
  },
  {
    char_id: 163,
    name: 'Storm (Ororo Munroe)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173012/mpq/storm5.png',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'green',
    power_three_color: 'yellow',
    feedee_id: 'none',
    feeder_id: 'Thor (Goddess of Thunder)',
    char_level: 255,
  },
  {
    char_id: 164,
    name: 'Juggernaut (Fear Itself)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173004/mpq/juggernaut5.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'red',
    power_three_color: 'blue',
    feedee_id: 'none',
    feeder_id: 'Magneto (Classic)',
    char_level: 70,
  },
  {
    char_id: 165,
    name: 'Rocket & Groot (Awesome Mix Volume 2)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173000/mpq/grocket4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'green',
    power_three_color: 'blue',
    feedee_id: 'none',
    feeder_id: 'Rocket & Groot (Most Wanted)',
    char_level: 70,
  },
  {
    char_id: 166,
    name: 'Wiccan (Billy Kaplan)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173015/mpq/wiccan4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'yellow',
    power_three_color: 'green',
    feedee_id: 'none',
    feeder_id: 'Scarlet Witch (Wanda Maximoff)',
    char_level: 70,
  },
  {
    char_id: 167,
    name: 'Kraven The Hunter (Sergei Kravinoff)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173005/mpq/kraven4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'purple',
    power_three_color: 'blue',
    feedee_id: 'none',
    feeder_id: 'Squirrel-Girl (Unbeatable)',
    char_level: 70,
  },
  {
    char_id: 168,
    name: 'Yondu (Awesome Mix Volume 2)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173016/mpq/yondu4.jpg',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'black',
    power_three_color: 'blue',
    feedee_id: 'none',
    feeder_id: 'Star Lord (Peter Quill)',
    char_level: 70,
  },
  {
    char_id: 169,
    name: 'Thanos (Endgame)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173013/mpq/thanos4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'blue',
    power_three_color: 'green',
    feedee_id: 'none',
    feeder_id: 'Thanos (Modern)',
    char_level: 70,
  },
  {
    char_id: 170,
    name: 'Sabretooth (Victor Creed)',
    image:
      'https://res.cloudinary.com/msccloud-40/image/upload/v1604173010/mpq/sabretooth4.png',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'black',
    power_three_color: 'red',
    feedee_id: 'none',
    feeder_id: 'Wolverine (Patch)',
    char_level: 70,
  },
];
