export const seedDB = [
  {
    name: 'America Chavez (Young Avengers)',
    image: 'america4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'yellow',
    power_three_color: 'green',
    feedees: 'Jessica Jones (Alias Investigations)',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Angel (All New X-Men)',
    image: 'angel3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'black',
    power_three_color: 'green',
    feedees: 'Nightcrawler (Classic),Jean Grey (All New X-Men)',
    shards: 0,
    char_level: 40,
  },
  {
    name: 'Ant-Man (Scott Lang)',
    image: 'antman4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'blue',
    power_three_color: 'yellow',
    feedees: 'Wasp (Hope Van Dyne)',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Ares (Dark Avengers)',
    image: 'ares2.webp',
    rarity: 2,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'red',
    power_three_color: 'yellow',
    feedees: 'Ragnarok (Dark Avengers)',
    shards: 0,
    char_level: 15,
  },
  {
    name: 'Beast (Classic)',
    image: 'beast3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'green',
    power_three_color: 'yellow',
    feedees: 'Jean Grey (All New X-Men),Jubilee (Uncanny X-Men)',
    shards: 0,
    char_level: 40,
  },
  {
    name: 'Black Bolt (Inhuman King)',
    image: 'blackbolt5.webp',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'black',
    power_three_color: 'yellow',
    feedees: 'none',
    shards: 0,
    char_level: 255,
  },
  {
    name: 'Black Panther (Civil War)',
    image: 'blackpanther5.webp',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'yellow',
    power_three_color: 'red',
    feedees: 'Black Panther (King of Wakanda)',
    shards: 0,
    char_level: 255,
  },
  {
    name: 'Black Panther (King of Wakanda)',
    image: 'blackpanther4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'blue',
    power_three_color: 'red',
    feedees: 'Black Panther (Civil War)',
    shards: 0,
    char_level: 70,
  },
  {
    name: "Black Panther (T'Challa)",
    image: 'blackpanther3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'blue',
    power_three_color: 'black',
    feedees: 'Black Panther (King of Wakanda)',
    shards: 0,
    char_level: 40,
  },
  {
    name: 'Black Widow (Natasha Romanoff)',
    image: 'blackwidow5.webp',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'red',
    power_three_color: 'black',
    feedees: 'none',
    shards: 0,
    char_level: 255,
  },
  {
    name: 'Black Widow (Infinity War)',
    image: 'blackwidow4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'purple',
    power_three_color: 'yellow',
    feedees: 'Black Widow (Natasha Romanoff)',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Black Widow (Grey Suit)',
    image: 'blackwidow3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'green',
    power_three_color: 'red',
    feedees: 'Nick Fury (Director of S.H.I.E.L.D.),Black Widow (Infinity War)',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Black Widow (Original)',
    image: 'blackwidow2.webp',
    rarity: 2,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'blue',
    power_three_color: 'black',
    feedees: 'Black Widow (Grey Suit)',
    shards: 0,
    char_level: 15,
  },
  {
    name: 'Blade (Modern)',
    image: 'blade4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'green',
    power_three_color: 'black',
    feedees: 'none',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Blade (Daywalker)',
    image: 'blade3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'purple',
    power_three_color: 'green',
    feedees: 'Blade (Modern)',
    shards: 0,
    char_level: 40,
  },
  {
    name: 'Bullseye (Dark Avengers)',
    image: 'bullseye2.webp',
    rarity: 2,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'black',
    power_three_color: 'green',
    feedees: 'Bullseye (Classic)',
    shards: 0,
    char_level: 15,
  },
  {
    name: 'Bullseye (Classic)',
    image: 'bullseye3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'black',
    power_three_color: 'green',
    feedees: 'Kingpin (Wilson Fisk)',
    shards: 0,
    char_level: 40,
  },
  {
    name: 'Captain America (The First Avenger)',
    image: 'captainamerica5.webp',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'red',
    power_three_color: 'blue',
    feedees: 'none',
    shards: 0,
    char_level: 255,
  },
  {
    name: 'Captain America (Infinity War)',
    image: 'infinitycap5.webp',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'purple',
    power_three_color: 'yellow',
    feedees: 'none',
    shards: 0,
    char_level: 255,
  },
  {
    name: 'Captain America (Super Soldier)',
    image: 'captainamerica3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'red',
    power_three_color: 'blue',
    feedees: 'Captain America (Worthy),Winter Soldier (Bucky Barnes)',
    shards: 0,
    char_level: 40,
  },
  {
    name: 'Captain America (Steve Rogers)',
    image: 'captainamerica2.webp',
    rarity: 2,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'red',
    power_three_color: 'blue',
    feedees: 'Captain America (Super Soldier)',
    shards: 0,
    char_level: 15,
  },
  {
    name: 'Captain Marvel (Galactic Warrior)',
    image: 'captainmarvel5.webp',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'green',
    power_three_color: 'yellow',
    feedees: 'none',
    shards: 0,
    char_level: 255,
  },
  {
    name: 'Captain Marvel (Carol Danvers)',
    image: 'captainmarvel4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'yellow',
    power_three_color: 'green',
    feedees: 'Captain Marvel (Galactic Warrior)',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Captain Marvel (Modern)',
    image: 'captainmarvel3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'yellow',
    power_three_color: 'green',
    feedees: 'Captain Marvel (Carol Danvers),Talos (Skrull Warlord)',
    shards: 0,
    char_level: 40,
  },
  {
    name: 'Captain Marvel (Ms. Marvel)',
    image: 'captainmarvel2.webp',
    rarity: 2,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'black',
    power_three_color: 'yellow',
    feedees: 'Captain Marvel (Modern)',
    shards: 0,
    char_level: 15,
  },
  {
    name: 'Carnage (Cletus Kassady)',
    image: 'carnage4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'black',
    power_three_color: 'green',
    feedees: 'Doctor Octopus (Classic)',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Colossus (Classic)',
    image: 'colossus3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'red',
    power_three_color: 'black',
    feedees: 'Wolverine (X-Force),Magik (Classic)',
    shards: 0,
    char_level: 40,
  },
  {
    name: 'Cyclops (Classic)',
    image: 'cyclops4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'yellow',
    power_three_color: 'blue',
    feedees: 'Cable (Nathan Summers)',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Cyclops (Uncanny X-Men)',
    image: 'cyclops3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'yellow',
    power_three_color: 'black',
    feedees: 'Cyclops (Classic),Emma Frost (Astonishing X-Men)',
    shards: 0,
    char_level: 40,
  },
  {
    name: 'Daken (Dark Avengers)',
    image: 'daken2.webp',
    rarity: 2,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'black',
    power_three_color: 'blue',
    feedees: 'Daken (Classic)',
    shards: 0,
    char_level: 15,
  },
  {
    name: 'Daken (Classic)',
    image: 'daken3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'purple',
    power_three_color: 'black',
    feedees: 'X-23 (All-New Wolverine)',
    shards: 0,
    char_level: 40,
  },
  {
    name: 'Daredevil (Man Without Fear)',
    image: 'daredevil3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'blue',
    power_three_color: 'red',
    feedees: 'Elektra (Unkillable)',
    shards: 0,
    char_level: 40,
  },
  {
    name: 'Daredevil (Matt Murdock)',
    image: 'daredevil5.webp',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'purple',
    power_three_color: 'green',
    feedees: 'none',
    shards: 0,
    char_level: 255,
  },
  {
    name: "Deadpool (It's Me, Deadpool!)",
    image: 'deadpool3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'purple',
    power_three_color: 'black',
    feedees: 'Deadpool (Uncanny X-Force),Domino (X-Force)',
    shards: 0,
    char_level: 40,
  },
  {
    name: 'Deadpool (Uncanny X-Force)',
    image: 'deadpool4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'black',
    power_three_color: 'purple',
    feedees: 'none',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Doctor Doom (Classic)',
    image: 'docdoom3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'blue',
    power_three_color: 'purple',
    feedees: 'Invisible Woman (Classic)',
    shards: 0,
    char_level: 40,
  },
  {
    name: 'Doctor Octopus (Otto Octavius)',
    image: 'dococtopus3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'black',
    power_three_color: 'green',
    feedees: 'Carnage (Cletus Kassady),Sandman (Flint Marko)',
    shards: 0,
    char_level: 255,
  },
  {
    name: 'Doctor Octopus (Classic)',
    image: 'droctopus5.webp',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'blue',
    power_three_color: 'green',
    feedees: 'none',
    shards: 0,
    char_level: 255,
  },
  {
    name: 'Doctor Strange (Stephen Strange)',
    image: 'drstrange3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'purple',
    power_three_color: 'yellow',
    feedees: 'Nova (Sam Alexander),Mordo (Master of the Mystic Arts)',
    shards: 0,
    char_level: 40,
  },
  {
    name: 'Doctor Strange (Sorcerer Supreme)',
    image: 'drstrange5.webp',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'purple',
    power_three_color: 'yellow',
    feedees: 'none',
    shards: 0,
    char_level: 255,
  },
  {
    name: 'Drax (The Destroyer)',
    image: 'drax4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'purple',
    power_three_color: 'red',
    feedees: 'Star Lord (Awesome Mix Volume 2)',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Elektra (Assassin)',
    image: 'elektra3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'black',
    power_three_color: 'red',
    feedees: 'Elektra (Unkillable)',
    shards: 0,
    char_level: 40,
  },
  {
    name: 'Elektra (Unkillable)',
    image: 'elektra4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'black',
    power_three_color: 'red',
    feedees: 'none',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Gambit (Modern)',
    image: 'bambit3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'red',
    power_three_color: 'black',
    feedees: 'Rogue (Classic),Dazzler (Classic)',
    shards: 0,
    char_level: 40,
  },
  {
    name: 'Gamora (Guardians of the Galaxy)',
    image: 'gamora3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'red',
    power_three_color: 'black',
    feedees: 'Star-Lord (Legendary Outlaw),Gamora (Awesome Mix Volume 2)',
    shards: 0,
    char_level: 40,
  },
  {
    name: 'Gamora (Awesome Mix Volume 2)',
    image: 'gamora4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'black',
    power_three_color: 'blue',
    feedees: 'Thanos (The Mad Titan)',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Ghost Rider (Robbie Reyes)',
    image: 'ghostrider5.webp',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'red',
    power_three_color: 'black',
    feedees: 'none',
    shards: 0,
    char_level: 255,
  },
  {
    name: 'Ghost Rider (Johnny Blaze)',
    image: 'ghostrider4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'red',
    power_three_color: 'black',
    feedees: 'Ghost Rider (Robbie Reyes)',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Green Goblin (Norman Osborn)',
    image: 'greengoblin5.webp',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'purple',
    power_three_color: 'yellow',
    feedees: 'none',
    shards: 0,
    char_level: 255,
  },
  {
    name: 'Gwenpool (Gwen Poole)',
    image: 'gwenpool4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'black',
    power_three_color: 'green',
    feedees: 'none',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Hawkeye (Clint Barton)',
    image: 'hawkeye5.webp',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'blue',
    power_three_color: 'red',
    feedees: 'none',
    shards: 0,
    char_level: 255,
  },
  {
    name: 'Hawkeye (Hawkguy)',
    image: 'hawkeye3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'blue',
    power_three_color: 'black',
    feedees: 'Kate Bishop (Hawkeye)',
    shards: 0,
    char_level: 15,
  },
  {
    name: 'Hawkeye (Modern)',
    image: 'hawkeye2.webp',
    rarity: 2,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'red',
    power_three_color: 'purple',
    feedees: 'Hawkeye (Hawkguy)',
    shards: 0,
    char_level: 15,
  },
  {
    name: 'Human Torch (Johnny Storm)',
    image: 'humantorch2.webp',
    rarity: 2,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'black',
    power_three_color: 'green',
    feedees: 'Human Torch (Classic)',
    shards: 0,
    char_level: 15,
  },
  {
    name: 'Human Torch (Classic)',
    image: 'humantorch3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'black',
    power_three_color: 'green',
    feedees: 'The Thing (Classic),Human Torch (Jim Hammond)',
    shards: 0,
    char_level: 40,
  },
  {
    name: 'The Hood (Classic)',
    image: 'hood3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'blue',
    power_three_color: 'black',
    feedees: 'Ghost Rider (Johnny Blaze)',
    shards: 0,
    char_level: 40,
  },
  {
    name: 'The Hulk (Indestructible)',
    image: 'hulk3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'black',
    power_three_color: 'green',
    feedees: 'The Hulk (Totally Awesome),The Hulk (Main Event)',
    shards: 0,
    char_level: 40,
  },
  {
    name: 'The Hulk (Totally Awesome)',
    image: 'chohulk4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'blue',
    power_three_color: 'black',
    feedees: 'The Hulk (Bruce Banner)',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'The Hulk (Main Event)',
    image: 'hulk4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'purple',
    power_three_color: 'yellow',
    feedees: 'Loki (God of Mischief)',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Iceman (All New X-Men)',
    image: 'iceman4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'blue',
    power_three_color: 'purple',
    feedees: 'Iceman (Bobby Drake)',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Invisible Woman (Classic)',
    image: 'iw4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'blue',
    power_three_color: 'green',
    feedees: 'none',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Iron Fist (Immortal Weapon)',
    image: 'ironfist3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'purple',
    power_three_color: 'black',
    feedees: 'Iron Fist (Danny Rand)',
    shards: 0,
    char_level: 40,
  },
  {
    name: 'Iron Fist (Danny Rand)',
    image: 'ironfist4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'green',
    power_three_color: 'black',
    feedees: 'none',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Iron Man (Mark XLVI)',
    image: 'ironman5.webp',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'red',
    power_three_color: 'blue',
    feedees: 'none',
    shards: 0,
    char_level: 255,
  },
  {
    name: 'Iron Man (Model 40)',
    image: 'ironman3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'blue',
    power_three_color: 'yellow',
    feedees: 'Iron Man (Hulkbuster),Riri Williams (Ironheart)',
    shards: 0,
    char_level: 40,
  },
  {
    name: 'Iron Man (Hulkbuster)',
    image: 'hulkbuster4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'black',
    power_three_color: 'blue',
    feedees: 'Rescue (Pepper Potts)',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Jean Grey (Phoenix)',
    image: 'phoenix5.webp',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'purple',
    power_three_color: 'red',
    feedees: 'none',
    shards: 0,
    char_level: 255,
  },
  {
    name: 'Jean Grey (All New X-Men)',
    image: 'jeangrey4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'purple',
    power_three_color: 'blue',
    feedees: 'none',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Jessica Jones (Alias Investigations)',
    image: 'jessicajones5.webp',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'black',
    power_three_color: 'blue',
    feedees: 'none',
    shards: 0,
    char_level: 255,
  },
  {
    name: 'Jubilee (Uncanny X-Men)',
    image: 'jubilee4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'purple',
    power_three_color: 'green',
    feedees: 'Jean Grey (Phoenix)',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Kamala Khan (Ms. Marvel)',
    image: 'msmarvel3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'purple',
    power_three_color: 'green',
    feedees: 'Medusa (Inhuman Queen),Lockjaw (Royal Bulldog)',
    shards: 0,
    char_level: 40,
  },
  {
    name: 'Kate Bishop (Hawkeye)',
    image: 'katebishop4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'black',
    power_three_color: 'purple',
    feedees: 'Hawkeye (Clint Barton)',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Kingpin (Spider-Verse)',
    image: 'kingpin5.webp',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'black',
    power_three_color: 'purple',
    feedees: 'none',
    shards: 0,
    char_level: 255,
  },
  {
    name: 'Kingpin (Wilson Fisk)',
    image: 'kingpin4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'purple',
    power_three_color: 'yellow',
    feedees: 'Daredevil (Matt Murdock)',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Loki (God of Mischief)',
    image: 'loki5.webp',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'green',
    power_three_color: 'black',
    feedees: 'none',
    shards: 0,
    char_level: 255,
  },
  {
    name: 'Loki (Dark Reign)',
    image: 'loki3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'purple',
    power_three_color: 'green',
    feedees: 'Venom (Eddie Brock),Mysterio (Quentin Beck)',
    shards: 0,
    char_level: 40,
  },
  {
    name: 'Luke Cage (Hero For Hire)',
    image: 'lukecage3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'red',
    power_three_color: 'black',
    feedees: 'Luke Cage (Power Man)',
    shards: 0,
    char_level: 40,
  },
  {
    name: 'Luke Cage (Power Man)',
    image: 'lukecage4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'black',
    power_three_color: 'red',
    feedees: 'none',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Magneto (Marvel NOW!)',
    image: 'magneto.webp',
    rarity: 2,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'purple',
    power_three_color: 'red',
    feedees: 'Magneto (Classic)',
    shards: 0,
    char_level: 15,
  },
  {
    name: 'Magneto (Classic)',
    image: 'magneto3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'blue',
    power_three_color: 'yellow',
    feedees: 'Professor X (Charles Xavier),Juggernaut (Fear Itself)',
    shards: 0,
    char_level: 40,
  },
  {
    name: 'Medusa (Inhuman Queen)',
    image: 'medusa4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'purple',
    power_three_color: 'green',
    feedees: 'Black Bolt (Inhuman King)',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Miles Morales (Spider-Man)',
    image: 'miles4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'yellow',
    power_three_color: 'red',
    feedees: 'Kingpin (Spiderverse)',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Moon Knight (Marc Spector)',
    image: 'moonknight4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'purple',
    power_three_color: 'green',
    feedees: 'none',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Moonstone (Dark Avengers)',
    image: 'moonstone2.webp',
    rarity: 2,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'black',
    power_three_color: 'red',
    feedees: 'The Hulk (Indestructible)',
    shards: 0,
    char_level: 15,
  },
  {
    name: 'Mordo (Master of the Mystic Arts)',
    image: 'mordo4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'blue',
    power_three_color: 'purple',
    feedees: 'Doctor Strange (Sorcerer Supreme)',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Mr. Fantastic (Reed Richards)',
    image: 'mrfantastic4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'yellow',
    power_three_color: 'black',
    feedees: 'Silver Surfer (Skyrider)',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Mystique (Raven Darkholme)',
    image: 'mystique3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'blue',
    power_three_color: 'black',
    feedees: 'Iceman (All New X-Men)',
    shards: 0,
    char_level: 40,
  },
  {
    name: 'Nick Fury (Director of S.H.I.E.L.D.)',
    image: 'nickfury4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'yellow',
    power_three_color: 'purple',
    feedees: 'none',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Nova (Sam Alexander)',
    image: 'nova4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'yellow',
    power_three_color: 'black',
    feedees: 'none',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Okoye (Warrior General)',
    image: 'okoye4.webp',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'yellow',
    power_three_color: 'red',
    feedees: 'none',
    shards: 0,
    char_level: 255,
  },
  {
    name: 'Peggy Carter (Captain America)',
    image: 'peggycarter4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'yellow',
    power_three_color: 'blue',
    feedees: 'Captain America (Super Soldier)',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Professor X (Charles Xavier)',
    image: 'profx4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'purple',
    power_three_color: 'yellow',
    feedees: 'Professor X (Classic)',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Psylocke (Classic)',
    image: 'psylocke3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'blue',
    power_three_color: 'black',
    feedees: 'Peggy Carter (Captain America)',
    shards: 0,
    char_level: 40,
  },
  {
    name: 'The Punisher (Dark Reign)',
    image: 'punisher3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'green',
    power_three_color: 'red',
    feedees: 'The Punisher (MAX)',
    shards: 0,
    char_level: 40,
  },
  {
    name: 'The Punisher (MAX)',
    image: 'punisher4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'green',
    power_three_color: 'blue',
    feedees: 'none',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Quake (Daisy Johnson)',
    image: 'quake4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'yellow',
    power_three_color: 'blue',
    feedees: 'none',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Quicksilver (Pietro Maximoff)',
    image: 'quicksilver3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'blue',
    power_three_color: 'green',
    feedees: 'War Machine (James Rhodes)',
    shards: 0,
    char_level: 40,
  },
  {
    name: 'Ragnarok (Dark Avengers)',
    image: 'ragnarok3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'green',
    power_three_color: 'red',
    feedees: 'Valkyrie (Asgardian Warrior),X-23 (All-New Wolverine)',
    shards: 0,
    char_level: 40,
  },
  {
    name: 'Red Hulk (Thunderbolt Ross)',
    image: 'redhulk4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'green',
    power_three_color: 'purple',
    feedees: 'none',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Rocket & Groot (Most Wanted)',
    image: 'grocket3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'green',
    power_three_color: 'blue',
    feedees: 'Drax (The Destroyer), Rocket & Groot (Awesome Mix Volume 2)',
    shards: 0,
    char_level: 40,
  },
  {
    name: 'Rogue (Classic)',
    image: 'rogue4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'red',
    power_three_color: 'yellow',
    feedees: 'Gambit (Classic)',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Sam Wilson (Falcon)',
    image: 'falcon3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'blue',
    power_three_color: 'purple',
    feedees: 'Sam Wilson (Captain America)',
    shards: 0,
    char_level: 40,
  },
  {
    name: 'Sam Wilson (Captain America)',
    image: 'samwilson4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'blue',
    power_three_color: 'red',
    feedees: 'none',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Sandman (Flint Marko)',
    image: 'sandman4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'purple',
    power_three_color: 'yellow',
    feedees: 'Green Goblin (Norman Osborn)',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Scarlet Witch (Wanda Maximoff)',
    image: 'scarletwitch3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'green',
    power_three_color: 'blue',
    feedees: 'Quake (Daisy Johnson),Wiccan (Billy Kaplan)',
    shards: 0,
    char_level: 40,
  },
  {
    name: 'Sentry (Dark Avengers)',
    image: 'sentry4.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'green',
    power_three_color: 'yellow',
    feedees: 'Moon Knight (Marc Spector)',
    shards: 0,
    char_level: 40,
  },
  {
    name: 'She-Hulk (Modern)',
    image: 'shehulk3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'green',
    power_three_color: 'red',
    feedees: 'Gwenpool (Gwen Poole)',
    shards: 0,
    char_level: 40,
  },
  {
    name: 'Shuri (Master Engineer)',
    image: 'shuri4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'green',
    power_three_color: 'red',
    feedees: 'Okoye (Warrior General)',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Silver Surfer (Skyrider)',
    image: 'silversurfer5.webp',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'red',
    power_three_color: 'black',
    feedees: 'none',
    shards: 0,
    char_level: 255,
  },
  {
    name: 'Spider-Man (Bag-Man)',
    image: 'spiderman2.webp',
    rarity: 2,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'blue',
    power_three_color: 'yellow',
    feedees: 'Spider-Man (Classic)',
    shards: 0,
    char_level: 15,
  },
  {
    name: 'Spider-Man (Back In Black)',
    image: 'bibsm5.webp',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'green',
    power_three_color: 'purple',
    feedees: 'none',
    shards: 0,
    char_level: 255,
  },
  {
    name: 'Spider-Man (Classic)',
    image: 'spiderman3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'yellow',
    power_three_color: 'blue',
    feedees: 'Miles Morales (Spider-Man)',
    shards: 0,
    char_level: 40,
  },
  {
    name: 'Spider-Man (Infinity War)',
    image: 'mcuspiderman4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'green',
    power_three_color: 'red',
    feedees: 'Spider-Man (Back In Black)',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Spider-Man (Peter Parker)',
    image: 'spiderman5.webp',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'green',
    power_three_color: 'red',
    feedees: 'none',
    shards: 0,
    char_level: 255,
  },
  {
    name: 'Spider-Woman (Jessica Drew)',
    image: 'spiderwoman4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'purple',
    power_three_color: 'red',
    feedees: 'none',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Squirrel-Girl (Unbeatable)',
    image: 'squirrelgirl3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'purple',
    power_three_color: 'green',
    feedees: 'Ant-Man (Scott Lang),Kraven The Hunter (Sergei Kravinoff)',
    shards: 0,
    char_level: 40,
  },
  {
    name: 'Star-Lord (Awesome Mix Volume 2)',
    image: 'starlord5.webp',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'purple',
    power_three_color: 'green',
    feedees: 'none',
    shards: 0,
    char_level: 255,
  },
  {
    name: 'Star-Lord (Legendary Outlaw)',
    image: 'starlord4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'yellow',
    power_three_color: 'red',
    feedees: 'none',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Star-Lord (Peter Quill)',
    image: 'starlord3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'yellow',
    power_three_color: 'red',
    feedees: 'Star-Lord (Legendary Outlaw)',
    shards: 0,
    char_level: 40,
  },
  {
    name: 'Storm (Classic)',
    image: 'storm2.webp',
    rarity: 2,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'blue',
    power_three_color: 'yellow',
    feedees: 'Storm (Mohawk)',
    shards: 0,
    char_level: 15,
  },
  {
    name: 'Storm (Mohawk)',
    image: 'storm3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'yellow',
    power_three_color: 'black',
    feedees: 'Thor (Goddess of Thunder)',
    shards: 0,
    char_level: 40,
  },
  {
    name: 'Thanos (The Mad Titan)',
    image: 'thanos5.webp',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'purple',
    power_three_color: 'green',
    feedees: 'none',
    shards: 0,
    char_level: 255,
  },
  {
    name: 'Thanos (Modern)',
    image: 'thanos3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'purple',
    power_three_color: 'green',
    feedees: 'Spider-Woman (Jessica Drew),Thanos (Endgame)',
    shards: 0,
    char_level: 40,
  },
  {
    name: 'The Thing (Classic)',
    image: 'thing4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'yellow',
    power_three_color: 'green',
    feedees: 'none',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Thor (Goddess of Thunder)',
    image: 'thor4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'yellow',
    power_three_color: 'blue',
    feedees: 'Storm (Ororo Munroe)',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Thor (Marvel NOW!)',
    image: 'thor2.webp',
    rarity: 2,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'yellow',
    power_three_color: 'green',
    feedees: 'Thor (Modern)',
    shards: 0,
    char_level: 15,
  },
  {
    name: 'Thor (Modern)',
    image: 'thor3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'yellow',
    power_three_color: 'green',
    feedees: 'Red Hulk (Thunderbolt Ross)',
    shards: 0,
    char_level: 40,
  },
  {
    name: 'Thor (Gladiator)',
    image: 'thor5.webp',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'red',
    power_three_color: 'yellow',
    feedees: 'none',
    shards: 0,
    char_level: 255,
  },
  {
    name: 'Valkyrie (Asgardian Warrior)',
    image: 'valkyrie4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'black',
    power_three_color: 'yellow',
    feedees: 'Thor (Gladiator)',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Venom (Eddie Brock)',
    image: 'venom4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'black',
    power_three_color: 'yellow',
    feedees: 'none',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Vision (Android Avenger)',
    image: 'vision3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'red',
    power_three_color: 'yellow',
    feedees: 'Wasp (Janet Vna Dyne)',
    shards: 0,
    char_level: 40,
  },
  {
    name: 'Vulture (Adrian Toomes)',
    image: 'vulture4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'green',
    power_three_color: 'blue',
    feedees: 'Spider-Man (Peter Parker)',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'War Machine (James Rhodes)',
    image: 'warmachine4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'blue',
    power_three_color: 'green',
    feedees: 'Iron Man (Mark XLVI)',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Wasp (Hope Van Dyne)',
    image: 'wasp5.webp',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'yellow',
    power_three_color: 'black',
    feedees: 'none',
    shards: 0,
    char_level: 255,
  },
  {
    name: 'Wasp (Janet Van Dyne)',
    image: 'wasp4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'blue',
    power_three_color: 'black',
    feedees: 'none',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Winter Soldier (Bucky Barnes)',
    image: 'wintersoldier4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'blue',
    power_three_color: 'red',
    feedees: 'Captain America (Infinity War)',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Wolverine (Astonishing X-Men)',
    image: 'wolverine2.webp',
    rarity: 2,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'red',
    power_three_color: 'yellow',
    feedees: 'Wolverine (Patch)',
    shards: 0,
    char_level: 15,
  },
  {
    name: 'Wolverine (Patch)',
    image: 'wolverine3.webp',
    rarity: 3,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'red',
    power_three_color: 'yellow',
    feedees: 'Wolverine (X-Force),Sabretooth (Victor Creed)',
    shards: 0,
    char_level: 40,
  },
  {
    name: 'Wolverine (Old Man Logan)',
    image: 'oldmanlogan5.webp',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'yellow',
    power_three_color: 'red',
    feedees: 'none',
    shards: 0,
    char_level: 255,
  },
  {
    name: 'Wolverine (X-Force)',
    image: 'wolverine4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'black',
    power_three_color: 'yellow',
    feedees: 'Wolverine (Old Man Logan)',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'X-23 (All-New Wolverine)',
    image: 'x234.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'red',
    power_three_color: 'purple',
    feedees: 'none',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Nightcrawler (Classic)',
    image: 'nightcrawler4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'red',
    power_three_color: 'blue',
    feedees: 'Archangel (Classic)',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Archangel (Classic)',
    image: 'archangel5.webp',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'green',
    power_three_color: 'black',
    feedees: 'none',
    shards: 0,
    char_level: 255,
  },
  {
    name: 'Captain America (Worthy)',
    image: 'worthycap4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'red',
    power_three_color: 'yellow',
    feedees: 'none',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Talos (Skrull Warlord)',
    image: 'talos4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'blue',
    power_three_color: 'black',
    feedees: 'none',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Magik (Classic)',
    image: 'magik4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'red',
    power_three_color: 'blue',
    feedees: 'Hela (Goddess of Death)',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Hela (Goddess of Death)',
    image: 'hela5.webp',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'green',
    power_three_color: 'black',
    feedees: 'none',
    shards: 0,
    char_level: 255,
  },
  {
    name: 'Emma Frost (Astonishing X-Men)',
    image: 'emmafrost4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'black',
    power_three_color: 'yellow',
    feedees: 'Kitty Pryde (Uncanny X-Men)',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Kitty Pryde (Uncanny X-Men)',
    image: 'kittypryde5.webp',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'purple',
    power_three_color: 'red',
    feedees: 'none',
    shards: 0,
    char_level: 255,
  },
  {
    name: 'Domino (X-Force)',
    image: 'domino4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'red',
    power_three_color: 'black',
    feedees: 'none',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Dazzler (Classic)',
    image: 'dazzler4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'red',
    power_three_color: 'green',
    feedees: 'none',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'The Hulk (Bruce Banner)',
    image: 'brucebanner5.webp',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'black',
    power_three_color: 'purple',
    feedees: 'none',
    shards: 0,
    char_level: 255,
  },
  {
    name: 'Hawkeye (Ronin)',
    image: 'ronin4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'red',
    power_three_color: 'purple',
    feedees: 'none',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Human Torch (Jim Hammond)',
    image: 'jimhammond4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'red',
    power_two_color: 'green',
    power_three_color: 'yellow',
    feedees: 'none',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Riri Williams (Ironheart)',
    image: 'ironheart4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'red',
    power_three_color: 'green',
    feedees: 'none',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Lockjaw (Royal Bulldog)',
    image: 'lockjaw.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'blue',
    power_three_color: 'green',
    feedees: 'none',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Mysterio (Quentin Beck)',
    image: 'mysterio4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'blue',
    power_three_color: 'yellow',
    feedees: 'none',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Iceman (Bobby Drake)',
    image: 'iceman5.webp',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'green',
    power_three_color: 'blue',
    feedees: 'none',
    shards: 0,
    char_level: 255,
  },
  {
    name: 'Doctor Doom (God Emperor)',
    image: 'docdoom5.webp',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'black',
    power_three_color: 'blue',
    feedees: 'none',
    shards: 0,
    char_level: 255,
  },
  {
    name: 'Rescue (Pepper Potts)',
    image: 'rescue5.webp',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'yellow',
    power_three_color: 'red',
    feedees: 'none',
    shards: 0,
    char_level: 255,
  },
  {
    name: 'Professor X (Classic)',
    image: 'profx5.webp',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'purple',
    power_three_color: 'black',
    feedees: 'none',
    shards: 0,
    char_level: 255,
  },
  {
    name: 'Gambit (Classic)',
    image: 'gambit5.webp',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'purple',
    power_two_color: 'red',
    power_three_color: 'black',
    feedees: 'none',
    shards: 0,
    char_level: 255,
  },
  {
    name: 'Storm (Ororo Munroe)',
    image: 'storm5.webp',
    rarity: 5,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'green',
    power_three_color: 'yellow',
    feedees: 'none',
    shards: 0,
    char_level: 255,
  },
  {
    name: 'Juggernaut (Fear Itself)',
    image: 'juggernaut5.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'red',
    power_three_color: 'blue',
    feedees: 'none',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Rocket & Groot (Awesome Mix Volume 2)',
    image: 'grocket4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'green',
    power_three_color: 'blue',
    feedees: 'none',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Wiccan (Billy Kaplan)',
    image: 'wican4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'blue',
    power_two_color: 'yellow',
    power_three_color: 'green',
    feedees: 'none',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Kraven The Hunter (Sergei Kravinoff)',
    image: 'kraven4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'purple',
    power_three_color: 'blue',
    feedees: 'none',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Yondu (Awesome Mix Volume 2)',
    image: 'yondu4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'yellow',
    power_two_color: 'black',
    power_three_color: 'blue',
    feedees: 'none',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Thanos (Endgame)',
    image: 'thanos4.webp',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'black',
    power_two_color: 'blue',
    power_three_color: 'green',
    feedees: 'none',
    shards: 0,
    char_level: 70,
  },
  {
    name: 'Sabretooth (Victor Creed)',
    image: '',
    rarity: 4,
    power_one_level: 0,
    power_two_level: 0,
    power_three_level: 0,
    power_one_color: 'green',
    power_two_color: 'black',
    power_three_color: 'red',
    feedees: 'none',
    shards: 0,
    char_level: 70,
  },
];
